### ISSUE TITLE
Is this a correct calculation of working memory?

### ISSUE THREAD

**Issue by leshchenko1979** [sourcery-ai/sourcery#103]
### Issue description or question

In the simple function below the working memory of 14 seems to be too high. Maybe the dicts increase this metric? I feel that they should not.

![image](https://user-images.githubusercontent.com/60138889/100351548-a4ea1380-2ffc-11eb-80df-7d0f7b89966d.png)

### Sourcery Version

0.8.3

### Code editor or IDE name and version

VS Code 1.51.1

### OS name and version

Windows 10 Pro 19041.630

**Comment by Hellebore** [comment]
It is indeed the dictionaries that are bumping up the working memory here. 

It's a really good point - we'll discuss it and have a good think about tweaking how it works.

**Comment by leshchenko1979** [comment]
My understanding is that anything that is a constant or consists of constants should not increase the working memory metric.

**Comment by Hellebore** [comment]
Our current calculation does include constants - after discussion we will leave it as it is for now. 

If you do have more examples where you think it is giving counter-intuitive results we would be keen to look at them.
