### ISSUE TITLE
Add refactoring for exclusive or

### ISSUE THREAD

**Issue by MiConnell** [sourcery-ai/sourcery#104]
### Issue description or question
Instead of writing code to check if values are `in` but also not equal to each other, use an exclusive or (`^`).

```python
my_list = [1, 2, 3, 4, 5]

first_index = 2
second_index = 4
goal = 3

""" -------before------- """
if (
    goal in (my_list[first_index], my_list[second_index])
    and my_list[first_index] != my_list[second_index]
):
    print("match found")
# also
if (
    goal == my_list[first_index]
    or goal == my_list[second_index]
    and my_list[first_index] != my_list[second_index]
):
    print("match found")


""" -----refactored----- """
if (goal == my_list[first_index]) ^ (goal == my_list[second_index]):
    print("match found")
```

### Sourcery Version

0.8.4

### Code editor or IDE name and version

VSCode 1.51.1

### OS name and version

OSX 11.0.1

**Comment by Hellebore** [comment]
Thanks for suggesting this! 

It does make the code shorter and more readable if you have a good grasp of exclusive or, but many developers don't.
On balance I think we won't add it in at the moment.
