### ISSUE TITLE
Refactor created function with one line between them

### ISSUE THREAD

**Issue by Tangerino** [sourcery-ai/sourcery#105]
Pycharm complains if functions are not two lines apart.

This happens when sourcery creates a new function

![image](https://user-images.githubusercontent.com/3164100/100871799-9c239280-347f-11eb-817e-f6785815fffa.png)

As an old C programmer, it seems more logical to add the new function above and not below the refactored code

**Comment by Hellebore** [comment]
Good catch - we've got it right for class methods but not base-level functions. Will look into fixing it.


As for ordering I prefer having the new function below the refactored code, and this is also what Pycharm's built-in method extraction tool does.
