### ISSUE TITLE
Unable to connect to Sourcery executable (sqlite3.OperationalError) no such table: disabled_functions

### ISSUE THREAD

**Issue by eli-cobler** [sourcery-ai/sourcery#111]
### Issue description or question
I keep getting the following error when sourcery is trying to run in the background. 

2:47 PM	Unable to connect to Sourcery executable
				(sqlite3.OperationalError) no such table: disabled_functions
				[SQL: 
				SELECT *
				FROM disabled_functions
				WHERE path=? and scopes=? and name=?
				]
				[parameters: ('path_to_python_file', '', 'function_it_is_trying_to_look_at')]
				(Background on this error at: http://sqlalche.me/e/13/e3q8)

### Sourcery Version
0.8.5

### Code editor or IDE name and version
Pycharm 2020.2.4 Professional

### OS name and version
OSX 10.15.7

**Comment by Hellebore** [comment]
Hi - are you also running VS Code on the same machine?

We just released a new vs code version that amends our local config database. The PyCharm version 0.8.6 which will be released by Jetbrains in the next day or two won't have this issue.

Apologies for this!

In the meantime you can try deleting the sourcery.db file which should be in Library/Application Support/sourcery .

**Comment by eli-cobler** [comment]
Yes I do. Ok not a huge deal I can just disable the ext for now and enable in a week or so.

**Comment by Hellebore** [comment]
Sourcery 0.8.6 has now been released in PyCharm, which resolves this issue.

**Comment by eli-cobler** [comment]
Just wanted to update and say I updated today and it works perfectly. Thanks again!
