### ISSUE TITLE
PyCharm plugin failed to start on update

### ISSUE THREAD

**Issue by Tangerino** [sourcery-ai/sourcery#113]
Just after upgrade PyCharm to 2020.3.1 Professional

I got this message

```
04:19	Failed to launch Sourcery service
			(sqlite3.OperationalError) no such table: device
			[SQL: SELECT device_id_value FROM device]
			(Background on this error at: http://sqlalche.me/e/13/e3q8)

```

**Comment by brendanator** [comment]
A couple of questions:
- Is it still occurring? There's some handling that should allow it to recover from errors like this
- Have you got the latest version of Sourcery 0.8.6?

If it isn't working try deleting the Sourcery database and restarting:
- Windows: `%APPDATA%\sourcery\sourcery.db`
- Mac: `~/Library/ApplicationSupport/sourcery/sourcery.db`
- Linux: `~/.config/sourcery/sourcery.db`

**Comment by Tangerino** [comment]
No, this was a one time event

**Comment by DeemOnSecurity** [comment]
I had a similar issue and just had to update the plugin to PyCharm.

**Comment by brendanator** [comment]
Thanks for the report. I'll close for now as it's now working for you both but will keep an eye on this in future
