### ISSUE TITLE
Option to ignore "low code quality" warning in Pycharm

### ISSUE THREAD

**Issue by simonkeys** [sourcery-ai/sourcery#116]
### Issue description or question

I have a function (pasted into my project for monkey-patching purposes) that triggers a "low code quality" (16%) warning. I don't want to refactor this code and I also don't want to see the warning flag on this file. Adding a `# sourcery skip` comment to the function has no effect. I'm guessing that this is because the "skip" comment turns off refactoring suggestions, but there is no refactoring suggested in this case.

It would be helpful if the `# sourcery skip` comment turned off all sourcery warnings for a particular function.

### Sourcery Version

0.8.7

### Code editor or IDE name and version

IntelliJ IDEA 2020.3.2 (Community Edition)
Build #IC-203.7148.57, built on January 25, 2021
Runtime version: 11.0.9.1+11-b1145.77 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.14.6
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
Non-Bundled Plugins: com.intellij.marketplace, com.intellij.plugins.watcher, net.seesharpsoft.intellij.plugins.csv, name.kropp.intellij.makefile, org.jetbrains.kotlin, de.halirutan.mathematica, PythonCore, sourcery.pycharm-plugin, nl.rubensten.texifyidea

Python Community Edition 203.7148.72

### OS name and version

macOS 10.14.6

**Comment by Hellebore** [comment]
Thanks for getting in touch! That's a great point - will definitely add this to our to-dos.

More generally do you find the low quality warnings useful and do you think the threshold is about right for triggering them?

**Comment by simonkeys** [comment]
The low-quality threshold seems good. It seems to agree with what I would judge by eye, so it doesn't really give me new information, but it is a good reminder that the code could use some improvement.

**Comment by Hellebore** [comment]
Addressed with release of 0.8.8 (currently pending approval by Jetbrains)
