### ISSUE TITLE
Use of continue clause causes for-loop-to-list-comprehension to be skipped

### ISSUE THREAD

**Issue by dericke** [sourcery-ai/sourcery#117]
### Issue description or question

When a `for` loop that builds a list includes a `continue` guard clause, Sourcery does not suggest the equivalent list comprehension:

```
mylist = [1, 2, 3, 4, 5]

mylist2 = []
for i in mylist:
    if i == 2:
        continue
    mylist2.append(i)
```
is equivalent to
```
mylist2 = [
    i for i in mylist if i != 2
]
```

### Sourcery Version

v0.8.7

### Code editor or IDE name and version

VS Code 1.53.0

### OS name and version

Ubuntu 20.04.2 LTS

**Comment by Hellebore** [comment]
Yep this looks like a nice change to make

**Comment by Hellebore** [comment]
Added with 0.9.1
