### ISSUE TITLE
'continue' should avoid simplify-numeric-comparison

### ISSUE THREAD

**Issue by Bengt** [sourcery-ai/sourcery#119]
### Issue description or question

I have test code something like this:

    def test():
        # Imagine some mocking and testing here
        # Test result data
        data = {
            'id': 17623467,
            'payload': 'my_payload_data',
        }
    
        # Test assertions
        for key in data.keys():
            if key == 'id':
                assert isinstance(data[key], int)
                continue
            if key == 'payload':
                assert isinstance(data[key], str)
                continue
            raise NotImplementedError(
                f'Please provide an assertion for key {key}.'
            )
    
Sourcery advises me to use `elif` here. That does however look inconsistent because `elif` is two characters longer than `if`. It is also unnecessary to create a switch-like expression, since all if-blocks use a `continue` statement. That fact is even checked for by raising the `NotImplementedError` at the end of the loop definition. So please make Sourcery not prompt me in this situation. :)

### Sourcery Version

0.8.7

### Code editor or IDE name and version

Pycharm 2020.3

### OS name and version

Linux

**Comment by Hellebore** [comment]
Good point!

**Comment by Hellebore** [comment]
Fixed in 0.9.1.

**Comment by Bengt** [comment]
Awesome. Thanks for the fix!
