### ISSUE TITLE
Sourcery AI WebSite Issue

### ISSUE THREAD

**Issue by thevillem** [sourcery-ai/sourcery#120]
### Issue description or question
Website is returning an error with message "Couldn't reach server. Please try again later."

Looking in the web console, it appears that there is a CORS policy missing from "api.sourcery.ai".

This is currently happening in Brave, Firefox, and Internet Explorer running on Windows 10.

I've attached a screenshot of the message and the error in the web console as well.

### Sourcery Version

0.8.7

### Code editor or IDE name and version

Visual Studio Code

### OS name and version

Windows

![message](https://user-images.githubusercontent.com/867487/109521852-bae3f600-7a7b-11eb-9cee-a3bb7f37f494.png)
![error in the web console](https://user-images.githubusercontent.com/867487/109521888-c6cfb800-7a7b-11eb-8fe8-96babca61949.png)

**Comment by brendanator** [comment]
Thanks for reporting this. I have investigated this issue and found a fix. Let me know if you have any more issues
