### ISSUE TITLE
Refactor unused list comprehension variable/index

### ISSUE THREAD

**Issue by marcoaaguiar** [sourcery-ai/sourcery#122]
### Issue description or question
When using list comprehension often times we don't use the variable/index of the iterator

```python
a = [object() for i in range(10)]
```

It could refactor to
```python
a = [object() for _ in range(10)]
```

### Sourcery Version

0.8.8

### Code editor or IDE name and version

Neovim 0.5

### OS name and version

Linux (WSL)

**Comment by Hellebore** [comment]
Yes this is a good idea!

**Comment by Hellebore** [comment]
Now done.
