### ISSUE TITLE
Sets should be used more often

### ISSUE THREAD

**Issue by henryiii** [sourcery-ai/sourcery#123]
### Issue description or question

Several of the methods seem to make lists instead of sets. For example, the refactoring here: https://github.com/henryiii/cibuildwheel/pull/1#discussion_r598904674 should add a set, not a list. (Also, unrelated, this one is wrong for me, since I do completeness checking with MyPy and MyPy doesn't like checking lists/sets, only `==`, for the type narrowing last I checked). The correct refactoring would be:

```diff
- if platform == 'linux':
+ if platform in {'linux', 'macos'}:
```

Set containership testing is faster, and is the more correct Python structure in this case.

### Sourcery Version

GitHub version (seen locally too).

**Comment by Hellebore** [comment]
I think for explicitly declared lists and sets used with 'in'  like these ones it doesn't make a performance difference. It got discussed on r/python a while back: https://www.reddit.com/r/Python/comments/j6n6wt/six_more_quick_ways_to_improve_your_python/g7zsvad?utm_source=share&utm_medium=web2x&context=3.

That's annoying about mypy!

**Comment by henryiii** [comment]
I don't get how you gathered that for that thread at all. It clearly says lists and tuples are identical, but sets are not (it makes a FrozenSet). And I can easily run the code listed; only in the special case of returning the first element in the list is a list faster. The Tuple version is constant performance, while the List/Tuple version depends on which element gets returned:

```python
from timeit import Timer
>>> def fn(value):
...     return value in ('USD', 'EUR')
...
>>> def fnS(value):
...     return value in {'USD', 'EUR'}
...
>>> Timer("fn('USD')", setup="from __main__ import fn").autorange()
(5000000, 0.3180129469999997)
>>> Timer("fn('EUR')", setup="from __main__ import fn").autorange()
(5000000, 0.38017736800000534)
Timer("fn('FOO')", setup="from __main__ import fn").autorange()
(5000000, 0.43637284700002965)

>>> Timer("fnS('USD')", setup="from __main__ import fnS").autorange()
(5000000, 0.3421709060000069)
>>> Timer("fnS('EUR')", setup="from __main__ import fnS").autorange()
(5000000, 0.33724936599998045)
>>> Timer("fnS('FOO')", setup="from __main__ import fnS").autorange()
(5000000, 0.34322814899996956)
```

With more elements, there is a different tradeoff, but the set is always a predictable constant time, which is really nice.

Finally, regurdless of the speed, the set is the logically correct construction. If you only use something for membership testing, it should be a set, not a linear array of items. The one special thing to worry about would be if these are not literals, that is, `x in {a, b}` does require a and b to be hashable (very likely if you are doing this sort of check, but not guaranteed).

**Comment by Hellebore** [comment]
Ah you're right - I misread the sets vs tuple/list difference!

Actually the point about them needing to be hashable may be the more important one for us in the general case, since we can't have any possibility of breaking the code in the case when they're not.

Will have a think about switching to sets where we know that it's a literal though. Thanks for putting the extra work in.

**Comment by Hellebore** [comment]
Note that the item that we are checking for membership (e.g `platform` in the first example) must also be a hashable type - this will restrict where we can use this refactoring to these situations.

**Comment by Hellebore** [comment]
Added in 0.9.1.
