### ISSUE TITLE
Unnecessary call to `bool()`

### ISSUE THREAD

**Issue by laike9m** [sourcery-ai/sourcery#129]
### Issue description or question

Code that Sourcery generated:
```python
return bool(frame and target in frame.f_builtins)
```
Calling `bool` is unnecessary. See [here](https://github.com/laike9m/Cyberbrain/pull/106#discussion_r606620724).

### Sourcery Version

GitHub app

**Comment by Hellebore** [comment]
Hi - due to short-circuiting, if `frame` evaluates to `False` then it will get returned straight away. This is why the call to `bool` is necessary - see the differing results from these two prints:
```
  frame = []
  print(bool(frame and False))
  print(frame and False)
```

**Comment by laike9m** [comment]
You're right
