### ISSUE TITLE
False positive 'redundant-if'

### ISSUE THREAD

**Issue by ntjess** [sourcery-ai/sourcery#131]
### Issue description or question
Sourcery thinks the following if-statement is redundant when it is not mutually exclusive:

```python
if not minimal or self.disabled:
  curState['disabled'] = self.disabled
elif not minimal:
  curState['allowDisable'] = self.allowDisable
```
![image](https://user-images.githubusercontent.com/23620506/115099323-33572700-9f03-11eb-9c17-4e8d5977f514.png)

### Sourcery Version
0.9.0

### Code editor or IDE name and version
PyCharm 2021.1 (Professional Edition)
Build #PY-211.6693.115, built on April 6, 2021
For educational use only.
Runtime version: 11.0.10+9-b1341.35 amd64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
Linux 5.8.0-48-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 1908M
Cores: 8
Non-Bundled Plugins: com.markskelton.one-dark-theme (5.1.5), pl.sudo.imageviewer.python (1.3.2), sourcery.pycharm-plugin (0.9.0)
Current Desktop: ubuntu:GNOME

**Comment by Hellebore** [comment]
I think Sourcery is correct here. The `elif` branch will never be executed. 

It would only be entered if `minimal` is `False`. However in this case the main `if` branch will be entered instead.
