### ISSUE TITLE
Working Memory -count is flawed

### ISSUE THREAD

**Issue by MartinPolygonflow** [sourcery-ai/sourcery#133]
### Issue description or question
The counter for the working memory adds up for pretty much everything, including:
Dictionary entries,
List comprehensions
Object properties

...and to me it's come to a point where I just find this feature annoying. Simple, lightweight functions still get a shit score because I happend to have a list comprehension or accessing too many properties of an object. I guess my frustration comes from the question: What should I do about this situation? Sourcery aims to help us write better code but in the cases of working memory the only way I see how things can be further improved is to start doing anti-pythonic things like not using list comprehensions and breaking down functions into even smaller, atomic-scale, functions which will have a counter-effect (ie: not be readable).

I'll provide an example (attached file). It's a very simple snippet of code in OpenMaya (Autodesk Maya 3D software) for getting the number of geometric components (edges, vertices, etc). I think it's a perfect example of when the 'Working Memory' counter goes bananas.
[working_memory_test.zip](https://github.com/sourcery-ai/sourcery/files/6390132/working_memory_test.zip)
![working_memory_test](https://user-images.githubusercontent.com/69456211/116369563-d06e6580-a809-11eb-8180-46ca35bfbf0a.jpg)

### Sourcery Version
0.9.0

### Code editor or IDE name and version

Pycharm v2020.3

### OS name and version

Windows 10 Pro

**Comment by Hellebore** [comment]
Thanks for taking the time to raise this, and for providing a clear example.

Will take a look and discuss it with my co-founder.

**Comment by Hellebore** [comment]
Hi - we're going to amend the calculation so that working memory doesn't get incremented for every value in a dictionary or argument in a method call, just taking the max value instead.

Could you elaborate on problems you've seen with list comprehensions, and any other cases you've seen where you didn't think working memory was working quite right?

**Comment by Hellebore** [comment]
This should substantially be addressed with 0.9.1
