### ISSUE TITLE
Refactoring with lambda functions

### ISSUE THREAD

**Issue by Anselmoo** [sourcery-ai/sourcery#136]
### Question: Any plans for refactoring via lambda functions?

Setting up your own lambda is sometimes not intuitive even if it helps to keep the code clean. Especially for the `Dictionary comprehension` and `Collection to comprehension`, I assume that the lambda functions have the possibility to further extend the functionality.

**Comment by Hellebore** [comment]
Hi, thanks for raising!

Could you give/point to a couple of examples of the kind of code transformation with lambdas that you'd like to see?

**Comment by Hellebore** [comment]
Closing until we get some more details.
