### ISSUE TITLE
Unable to connect to Sourcery executable

### ISSUE THREAD

**Issue by LP-Codes** [sourcery-ai/sourcery#139]
### Issue description or question

Getting Error on Pycharm Unable to connect to Sourcery executable though works on vscode 

Unable to connect to Sourcery executable
			(sqlite3.OperationalError) no such table: disabled_functions
			[SQL: 
			SELECT *
			FROM disabled_functions
			WHERE path=? and scopes=? and name=?
			]
			[parameters: ('D:/dummy3.py', '', 'resize_base64_image')]
			(Background on this error at: http://sqlalche.me/e/e3q8)

### Sourcery Version

0.3.3 -dev

### Code editor or IDE name and version

Pycharm v?

2021.1.1

### OS name and version

Windows

**Comment by Hellebore** [comment]
Hi - could you try updating the Sourcery plugin in PyCharm?
Should be something like File > Settings > Plugins, then find sourcery and click update.

**Comment by LP-Codes** [comment]
Hello Hellebore its already updated to the latest version , I even tried uninstalling & doing a fresh install but didn't help , but seems to work properly on Vscode

**Comment by Hellebore** [comment]
That's weird - I was just going by the 0.3.3-dev on the issue, which is qute an old version. Which sourcery version does it say in PyCharm?

**Comment by LP-Codes** [comment]
Plugin version is 0.3.3.-dev , Sourcery Verion is 0.5.11

**Comment by Hellebore** [comment]
Oh were you on the original alpha? The current version should be 0.9.0.
If you click on the cog in the top right of the plugins settings page and go to 'manage custom repositories' is there an entry for Sourcery? If there is could you try deleting it?

**Comment by LP-Codes** [comment]
This Helped Thanks  -- go to 'manage custom repositories' is there an entry for Sourcery? If there is could you try deleting it?
now the version is 0.9.0
