### ISSUE TITLE
High resource memory & cpu consumption on VSCode close

### ISSUE THREAD

**Issue by lmmentel** [sourcery-ai/sourcery#141]
### Issue description or question

I noticed that when I close VSCode sourcery start consuming a lot of resources CPU + memory (> 4.5GB), see screenshot. Happens almost every time. I had troubles with the same issue some time ago (see #60) and the issue was fixed for some time but now I'm seeing the same problems again. 

I tried uninstalling sourcery and reinstalling it but it didn't help

![image](https://user-images.githubusercontent.com/8989838/121169082-ee40d880-c853-11eb-974a-44d5116d2feb.png)

### Sourcery Version

sourcery: 0.9.0

### Code editor or IDE name and version

VSCode: 1.56.2

### OS name and version

 OS: Linux mint 20.1 5.4.0-73-generic

**Comment by Hellebore** [comment]
Thanks for raising - will look into this.

Couple of questions to help me narrow it down:
- Are you working with projects that have large files/function sizes?
- Are you using the 'Sourcery - scan for refactorings/detect clones' commands from the right-click menu?

**Comment by lmmentel** [comment]
> Are you working with projects that have large files/function sizes?

I wouldn't say so (depending on your definition of large) but the largest files have 1.5k lines and the functions are way smaller than that. It happened on several different projects where the distribution of files/functions differs.

> Are you using the 'Sourcery - scan for refactorings/detect clones' commands from the right-click menu?

No, I haven't tried that yet. I'm relying on the scan that is triggered on file save.

**Comment by Hellebore** [comment]
Thanks. So is it only when you close vs code that the resources heap up?

Could you send over your Sourcery log file to nick at sourcery dot ai?
It should be in .local/share/sourcery/sourcery.log

**Comment by Hellebore** [comment]
Thanks for the logs! Can see the problem - will need to make a fix.

**Comment by lmmentel** [comment]
Great! Looking forward to it. Thanks for such a rapid response!

**Comment by Hellebore** [comment]
Should now be fixed with 0.9.3 - let us know if you still have issues.

**Comment by apcamargo** [comment]
Hey! I'm still having this issue with 0.9.3. The process is still running even after I close VSCode.

VSCode 1.58.2
macOS 11.3.1 (although I had the same problem in Ubuntu 18.04 sometime ago)
