### ISSUE TITLE
Metrics hover shows in the wrong place for decorated functions

### ISSUE THREAD

**Issue by Hellebore** [sourcery-ai/sourcery#142]
### Issue description or question

Where a function has a decorator the metrics hover shows on the decorator line rather than the function definition.

### Sourcery Version

0.9.1

### Code editor or IDE name and version

VS Code

### OS name and version

All

**Comment by brendanator** [comment]
Store the function offset position in the CodeLocation. Look for first def in code section

**Comment by Hellebore** [comment]
Fixed in 0.9.6
