### ISSUE TITLE
Refactoring causes indentation not consistent with rest of file

### ISSUE THREAD

**Issue by ThisIsanAlt** [sourcery-ai/sourcery#143]
### Issue description or question
Sourcery will refactor code and add additional, unwanted indentation that is not consistent with the rest of my file. In my case, sourcery converts my indentation into 8 spaces instead of 4 that is used elsewhere.

### Sourcery Version
0.9.1

### Code editor or IDE name and version

VSCode 1.5.7

### OS name and version

Windows 21H1 19043.1052

**Comment by Hellebore** [comment]
Hi - thanks for raising! Could you provide a code snippet that I can use to reproduce the issue?

**Comment by ThisIsanAlt** [comment]
I've tried reproducing the issue in other files/with the function by itself, turns out I can't reproduce the issue without the entire file. It happens when Sourcery attempts to refactor the entire function instead of the singular if/elif clause.

Sourcery trying to refactor code with the entire file:
![Screenshot 2021-06-15 120050](https://user-images.githubusercontent.com/50222844/122086145-6e75b980-cdd1-11eb-8900-f2da417d429b.png)
![Screenshot 2021-06-15 120113](https://user-images.githubusercontent.com/50222844/122086153-6f0e5000-cdd1-11eb-8421-f75480f6f64d.png)

Standalone function refactoring:
![Screenshot 2021-06-15 120336](https://user-images.githubusercontent.com/50222844/122086534-cb716f80-cdd1-11eb-884a-c5920e10f909.png)
![Screenshot 2021-06-15 120350](https://user-images.githubusercontent.com/50222844/122086538-cd3b3300-cdd1-11eb-858f-5babb57cf6f6.png)

Main code in txt:
If you mess with the if statements at lines ~60, ~115, or ~216, sourcery refactors the entire function instead of the specific if/elif clause and adds incorrect indentation.
[code.txt](https://github.com/sourcery-ai/sourcery/files/6657074/code.txt)

**Comment by Hellebore** [comment]
Cheers for posting the code!

Sourcery is taking the indent from the first indent it finds in the file - that's the 8 space indent in recieve_api_key.
If this indent is corrected to 4 spaces it all works nicely.

Agree that it would be better in this case to do this on a per-function basis but will be leaving it for now, since it's rare to have differing indent levels in a file.
