### ISSUE TITLE
Sourcery looks like broken.

### ISSUE THREAD

**Issue by MisileLab** [sourcery-ai/sourcery#148]
### Issue description or question

I make nested_if code for test sourcery, but it doesn't give issue and refactor.
![image](https://user-images.githubusercontent.com/74066467/128621800-094163cd-6746-4f84-a6bd-46f827dceb67.png)
also code metrics doesn't give code quality.
![image](https://user-images.githubusercontent.com/74066467/128621810-bcbeeda3-0eb8-45bd-8e41-0e3f08d8dd20.png)

### Sourcery Version

0.9.3

### Code editor or IDE name and version

Pycharm 2021.2

### OS name and version

Windows

**Comment by Hellebore** [comment]
Hi - what is displayed in the Sourcery tool window, and are there any error notifications displayed on startup?

**Comment by MisileLab** [comment]
> Hi - what is displayed in the Sourcery tool window, and are there any error notifications displayed on startup?

no error
Sourcery tool window
![image](https://user-images.githubusercontent.com/74066467/128705610-277bc356-38a4-4248-8ee3-e39ca2877e89.png)

**Comment by Hellebore** [comment]
Thanks for those details - could you please send over your log file to nick at sourcery dot ai?

It should be here:
%LOCAL_APP_DATA%/sourcery/sourcery.log or %APP_DATA%/sourcery/sourcery.log

**Comment by MisileLab** [comment]
I don't know what is pycharm log because i use vscode and pycharm together and vscode just start correctly.
I will give all of logs.

https://sen0733-my.sharepoint.com/:u:/g/personal/misile_munchang_sen_ms_kr/EXZ9dWvZb_hChYAeZPRyLDkBcNkmkMmWDNy9cTgkRS0KhQ?e=MLM6gG
