### ISSUE TITLE
'scan for refactorings' and 'detect clones' not working in remotessh

### ISSUE THREAD

**Issue by arulprakash8806** [sourcery-ai/sourcery#151]
### Issue description or question
'scan for refactorings' and 'detect clones' not working in remotessh. I see an unhandled exception
```
  workbench.desktop.main.js:2036 Error: KeyError: 'fsPath'
	at handleResponse (vscode-file://vscode…rpc/lib/main.js:436)
	at processMessageQueue (vscode-file://vscode…rpc/lib/main.js:263)
	at Immediate.<anonymous> (vscode-file://vscode…rpc/lib/main.js:247)
	at processImmediate (internal/timers.js:461)
```

### Sourcery Version
v0.9.3

### Code editor or IDE name and version

vscode 1.59.1

### OS name and version

centos 7
OS Version:       Linux x64 3.10.0-1160.25.1.el7.x86_64

**Comment by arulprakash8806** [comment]
any update on this?

**Comment by bm424** [comment]
This should be fixed in the next release, feel free to re-open if the issue persists.
