### ISSUE TITLE
Python variables named "package" confusing analysis

### ISSUE THREAD

**Issue by greyblue9** [sourcery-ai/sourcery#152]
### Issue description or question
When a python module includes variables named `package`, the analysis gets confused and will report the wrong names for some functions such as:
```_find_entry_point._venv_pkg_path._clean_sys_modules._venv_root._load_venv_mod._extracted_from__load_venv_mod_54._build_mod.Use._use_str```
If the variables are renamed (e.g. to `package_name`), these issues disappear.

Screenshot showing issue in Sourcery PR comment:
![Screenshot_20210829-074431](https://user-images.githubusercontent.com/5016549/131249267-e3f87a7f-98d2-441b-911f-28464d6c37c1.png)

Example of an affected PR:
https://github.com/amogorkon/justuse/pull/184

Example PR showing result with `package` variables renamed:
https://github.com/amogorkon/justuse/pull/185

### Sourcery Version
Sorcery GitHub online (pull request comments)

### Code editor or IDE name and veversion
GitHub

### OS name and version
N/A

**Comment by Hellebore** [comment]
Have reproduced this. Will investigate.

**Comment by greyblue9** [comment]
> Have reproduced this. Will investigate.

Thanks! 🥳

**Comment by bm424** [comment]
Hi @greyblue9, I've just pushed a change and this issue should be fixed in the next release of Sourcery. Thanks for flagging it!

**Comment by greyblue9** [comment]
You're welcome! Really appreciate your response and thanks for the fix!
