### ISSUE TITLE
Wrong `de-morgan` inequality refactoring for non-numerical types

### ISSUE THREAD

**Issue by ruancomelli** [sourcery-ai/sourcery#153]
### Issue description or question

Refactoring inequality comparisons using De Morgan's identities works fine for real numbers and results in more readable code. For instance, the following piece of code:
```py
x, y = 0, 1

if not (x <= y):
    print("Invalid `x` and `y`")
```
gets refactored as
```py
x, y = 0, 1

if x > y:
    print("Invalid `x` and `y`")
```

However, swapping `not (x <= y)` with `x > y` is only valid for *some types*, such as `float` and `int`, but invalid to many other types, such as `set`s:
```py
x, y = set(), set()

if not (x <= y):
    print('`x` is not a subset of `y`')
```
In this case, `not (x <= y)` is *not* equivalent to `x > y` (the former means "*x* is not a subset of *y*", whereas the latter means "*x* is a strict superset of *y*").

More generally,
```py
class X:
    def __le__(self, other) -> bool:
        return True

x, y = X(), X()

if not (x <= y): ...
```
is fine, but will raise `TypeError: '>' not supported between instances of 'X' and 'X'` if we accept Sourcery's suggestion to replace `not (x <= y)` with `x > y`.

In my opinion, the simplest way to avoid this mistake is to restrict this kind of refactoring to instances and subtypes of [`numbers.Real`](https://docs.python.org/3/library/numbers.html#numbers.Real) that do not define custom comparison operators.

### Sourcery Version

0.9.4

### Code editor or IDE name and version

VS Code v1.59.1 (x64)

### OS name and version

Ubuntu 20.04.3 LTS

**Comment by Hellebore** [comment]
Fixed in 0.9.6
