### ISSUE TITLE
Squiggly blue line on comment instead of code

### ISSUE THREAD

**Issue by half-of-a-glazier** [sourcery-ai/sourcery#155]
### Issue description or question
Sourcery puts the squiggly blue line underneath the commented code instead of the actual line of code.

![image](https://user-images.githubusercontent.com/44804291/131658332-3fcee221-e649-4035-b367-51364ccf2629.png)

![image](https://user-images.githubusercontent.com/44804291/131658346-a2c48b78-3ff7-4bdb-8fbc-7ee65125bc66.png)

### Sourcery Version
Not sure where to find this

### Code editor or IDE name and version
VS Code
Version: 1.58.2 (system setup)
Commit: c3f126316369cd610563c75b1b1725e0679adfb3
Date: 2021-07-14T22:10:15.214Z
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19043

### OS name and version
Windows
Edition	Windows 10 Enterprise for Virtual Desktops
Version	21H1
Installed on	‎17/‎06/‎2021
OS build	19043.1165

**Comment by brendanator** [comment]
Sourcery is accidentally deleting the comment, hence it's highlighting that line as it's the first to change

**Comment by Hellebore** [comment]
Handling deletion of comments is currently a limitation of our technology - this is something we will be working to address but not for a while.

**Comment by Hellebore** [comment]
This should be fixed with release of 0.12.8
