### ISSUE TITLE
New user Pro features not working in VSCode

### ISSUE THREAD

**Issue by walterg2** [sourcery-ai/sourcery#156]
### Issue description or question
Sourcery user key during 30-day trial does not allow the user to use any Pro features in VSCode.

Steps to reproduce:
1. Create a new Sourcery account using my GitHub login
2. Add the Sourcery extension to VSCode
3. Apply the token given
4. Restart VSCode to ensure everything takes effect
5. Right click on a folder to be analyzed
6. Choose `Sourcery` -> `Scan for Refactorings`
7. Receive message `Upgrade to Sourcery Pro for this feature`

This also occurs for the menu item of `Detect Clones`.

I have also attempted to reset my token inside my profile to no avail.

I'd really love to try these features (as your site and marketing materials suggest I can as a new user) before formally pulling the trigger to purchase.

### Sourcery Version
v0.9.3

### Code editor or IDE name and version

VSCode 1.59.1

### OS name and version

OSX (BigSur 11.5.2)

**Comment by Hellebore** [comment]
Very sorry you're having this issue - you should indeed have the Pro features. Will investigate and let you know.

**Comment by Hellebore** [comment]
OK this should now be resolved - please let us know if it's working for you after a restart.
