### ISSUE TITLE
Bogus `remove-redundant-if` suggested as `global` variable scope not taken into account

### ISSUE THREAD

**Issue by umaplehurst** [sourcery-ai/sourcery#158]
### Issue description or question

So I have this code in a script, which when executed will always call the `print(...)`:

```
report_data = {}
def really_do_some_external_comms_and_set_dict_key():
    global report_data
    report_data['branch'] = 123

if 'branch' not in report_data:
	really_do_some_external_comms_and_set_dict_key()
	if 'branch' not in report_data:
		sys.exit(1)

print(report_data)
```

But Sourcery suggests refactoring it to this (via "`remove-redundant-if`"):
But this changed code will never call the `print(...)` any more:

```
report_data = {}
def really_do_some_external_comms_and_set_dict_key():
    global report_data
    report_data['branch'] = 123

if 'branch' not in report_data:
    really_do_some_external_comms_and_set_dict_key()
    sys.exit(1)

print(report_data)
```

It looks like the problem is that Sourcery does not consider the `global` scope of the `report_data` variable.

### Sourcery Version

v0.9.4

### Code editor or IDE name and version

VS Code 1.59.1

### OS name and version

Linux

**Comment by Hellebore** [comment]
Fixed in 0.9.6
