### ISSUE TITLE
GitHub reporting: edit existing comment

### ISSUE THREAD

**Issue by casperdcl** [sourcery-ai/sourcery#163]
### Issue description or question

When posting reports as GitHub comments, any existing report is deleted and a new one posted. This is wrong since it will trigger email notifications spam each time a commit is pushed to a PR.

Instead, sourcery should follow standard practices of other reporting tools and edit (update) its existing comments.

See e.g. https://github.com/tqdm/tqdm/pull/1246 for an example of Codecov editing its reports each commit while Sourcery triggers dozens of spam emails.

**Comment by Hellebore** [comment]
We now try to update the existing comment rather than deleting and re-adding.
