### ISSUE TITLE
`class-extract-method` shows in tooltip but isn't on https://github.com/sourcery-ai/sourcery/wiki/Current-Refactorings

### ISSUE THREAD

**Issue by pzelnip** [sourcery-ai/sourcery#164]
### Issue description or question

I have sourcery flagging some lines in my project as being suitable to extract into a method, but the tooltip (as seen in the screenshot below) says this is the `class-extract-method` refactor, but upon clicking that link I'm taken to https://github.com/sourcery-ai/sourcery/wiki/Current-Refactorings#class-extract-method and there doesn't appear to be a 
`class-extract-method` refactoring listed there (just `extract-method`)

![image](https://user-images.githubusercontent.com/414933/134985174-80b0a76b-469c-4d7f-b08c-239057bf88fb.png)

I'm assuming that this is a typo, and the link should actually be: https://github.com/sourcery-ai/sourcery/wiki/Current-Refactorings#extract-method (the "Extract Method" refactoring).

### Sourcery Version

VS Code plugin: v0.9.5

### Code editor or IDE name and version

VS Code:

Version: 1.60.2
Commit: 7f6ab5485bbc008386c4386d08766667e155244e
Date: 2021-09-22T11:59:27.195Z (5 days ago)
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 19.6.0

### OS name and version

OSX: Darwin x64 19.6.0

**Comment by Hellebore** [comment]
Fixed.
