### ISSUE TITLE
Simplify dictionary update

### ISSUE THREAD

**Issue by emorozov** [sourcery-ai/sourcery#165]
### Issue description or question
I often see the code like:
```py
def foo(d: dict) -> None:
   d.update({'request': HttpRequest()})
   frobnicate(d)
```

Here `.update` can and should be replaced with:
```py
d['request'] = HttpRequest()
```

### Sourcery Version

0.9.5

### Code editor or IDE name and version

Pycharm v2021.2.2

### OS name and version

Arch Linux (Linux lenovo 5.14.7-arch1-1 #1 SMP PREEMPT Wed, 22 Sep 2021 21:35:11 +0000 x86_64 GNU/Linux)

**Comment by Hellebore** [comment]
yeah this looks like a nice little improvement

**Comment by Hellebore** [comment]
Added in 0.9.6
