### ISSUE TITLE
Convert list comprehensions to generators in function calls

### ISSUE THREAD

**Issue by emorozov** [sourcery-ai/sourcery#166]
### Issue description or question
Code like
```py
l = ['a', 'b', 'c']
s = ','.join([e for e in l])
```

Can be replaced with:
```py
l = ['a', 'b', 'c']
s = ','.join(e for e in l)
```

Second version doesn't create an extra dictionary and looks a bit cleaner. Although this is probably subjective. Maybe it is also more efficient on iterables with many items (performance on few items is comparable).

### Sourcery Version

0.9.5

### Code editor or IDE name and version

Pycharm v2021.2.2

### OS name and version

Arch Linux (Linux lenovo 5.14.7-arch1-1 #1 SMP PREEMPT Wed, 22 Sep 2021 21:35:11 +0000 x86_64 GNU/Linux)

**Comment by Hellebore** [comment]
`str.join` is actually a method where we're changing it to not suggest removing the comprehension (for performance reasons - see https://github.com/sourcery-ai/sourcery/issues/150).

Are there other cases where you think we should be suggesting this change and we're not currently?
