### ISSUE TITLE
Type hints make it harder for Sourcery to identify refactoring opportunities

### ISSUE THREAD

**Issue by ruancomelli** [sourcery-ai/sourcery#167]
### Issue description or question

Variable type annotations make it harder (or impossible) for Sourcery to identify refactorings in the code. For instance, whereas Sourcery correctly suggests converting the `for` loop into a list comprehension in this case:
```py
my_list = []
for i in range(10):
    my_list.append(i)
```
I get no suggestions from Sourcery if I type-annotate `my_list`:
```py
# no `list-comprehension`
my_list: list[int] = []
for i in range(10):
    my_list.append(i)
```

Other kinds of refactorings suffer from this as well:
```py
# no `dict-comprehension`
my_dict: dict[str, int] = {}
for name in ('Hercule Poirot', 'Sherlock Holmes'):
    my_dict[name] = len(name)

# no `dict-literal`
x: dict[int, float] = dict()

# ... and possibly many others
```

### Sourcery Version

v0.9.5

### Code editor or IDE name and version

VS Code 1.61.2 (x64)

### OS name and version

Ubuntu 20.04.3 LTS

**Comment by Hellebore** [comment]
These examples now work in Sourcery 0.10.2
