### ISSUE TITLE
UnboundLocalError when using assignment expressions and merge-nested-if together

### ISSUE THREAD

**Issue by diceroll123** [sourcery-ai/sourcery#170]
### Issue description or question
For a function that returns an optional value -- when it *doesn't* return None, will cause an UnboundLocalError due to walrus operator not actually making the variable, after merging nested ifs.

It's easier with a screenshot. The code uses random to show that it only breaks when the optional function returns the non-None value. You may need to run the code multiple times to throw an error. -shrug- See attached.

![image](https://user-images.githubusercontent.com/1243957/140629815-d207b859-d7df-4f62-b564-efc88befedf1.png)

### Sourcery Version

0.9.5

### Code editor or IDE name and version

VSC
Version: 1.61.2 (user setup)
Commit: 6cba118ac49a1b88332f312a8f67186f7f3c1643
Date: 2021-10-19T14:57:20.575Z
Electron: 13.5.1
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22489

### OS name and version

Windows

**Comment by Hellebore** [comment]
Definite bug - will address.

**Comment by Hellebore** [comment]
Looks like we need to wrap the assignment expression in an extra pair of brackets here to fix this.

**Comment by diceroll123** [comment]
Yep, that's what the PEP says to do. Until you said it, I completely forgot!
