### ISSUE TITLE
Choose subset of multiple refactoring options to apply on a per-block basis? 

### ISSUE THREAD

**Issue by rowlesmr** [sourcery-ai/sourcery#172]
### Issue description or question

When there are multiple refactoring options for a given block of code, I can't see how to only apply a certain subset of the suggestions.

eg

```
# `patterns` is a dictionary-like object
for pattern in patterns:
    cannot = ["OPT1", "OPT2", ]
    can = ["OPT3", "OPT4", "OP5"]
    if any(x in pattern for x in cannot) and not any(x in pattern for x in can):
        pattern.RemoveItem("ID")
```
wants to 
```
Hoist statements out of for/while loops(hoist-statement-from-loop)
Invert any/all to simplify comparisons(invert-any-all)
```

How do I choose just to apply the hoist?

### Sourcery Version

0.9.6

### Code editor or IDE name and version

PyCharm 2021.2.3 (Community Edition)
Build #PC-212.5457.59, built on October 19, 2021
Runtime version: 11.0.12+7-b1504.40 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2024M
Cores: 8
Non-Bundled Plugins: sourcery.pycharm-plugin (0.9.6)

### OS name and version

Windows 10

**Comment by Hellebore** [comment]
There's no way of doing this at present, but we are currently working on this feature - should hopefully be in our next release!

**Comment by Hellebore** [comment]
Live with 0.11.2. Where we can present refactorings in a function separately we now do so - those that affect the same chunk of code or that depend on each other are still combined.
