### ISSUE TITLE
"Inline variable that is immediately returned" drops type information

### ISSUE THREAD

**Issue by Bengt** [sourcery-ai/sourcery#174]
### Issue description

I have code something like this:

```Python3
import random

def get_random_integer() -> int:
    random_integer: int = random.choice(range(0, 11))

    return random_integer
```

Sourcery suggests inlining the variable, although that removes the type info:

![scratch](https://user-images.githubusercontent.com/11575/144885982-1fb94756-346a-448a-a2c7-09724877b708.png)

### Sourcery Version

0.9.7

### Code editor or IDE name and version

Pycharm v2021.3

### OS name and version

Ubuntu Linux 20.04

**Comment by reka** [comment]
Hey Bengt,

Thanks a lot for opening this issue. We've recently introduced some changes to recognize refactorings for type annotated code and are happy to hear feedback and comments about this topic. :slightly_smiling_face: 

Regarding the example: 
It's true that a type annotation disappears with the inlining, but as far as I see, there's no loss of type information.

`mypy` 0.910 finds both the original and the refactored code valid.

Original code:

```
import random

def get_random_integer() -> int:
    random_integer: int = random.choice(range(0, 11))

    return random_integer
```

Refactored code:

```
import random

def get_random_integer() -> int:
    return random.choice(range(11))
```

* The function `get_random_integer` is still annotated with a return value `int`.
* mpy recognizes that `random.choice(range(11))` will always return an int.

When we change the parameter of `random.choice` e.g. to a sequence of strings, `mypy` recognizes the problem both in the original and in the refactored version:

```
import random

def get_random_integer() -> int:
    return random.choice(['a','b','c'])
```

=> error: Incompatible return value type (got "str", expected "int")

So, we can remove the `random_integer` local variable without loosing type information.

Let me know if you have further questions or other examples.

**Comment by Bengt** [comment]
Hello @reka,

thanks for your reply and sorry I am only responding now.

I understand that the type of `random_integer` can still be infererred after the refactoring suggested by sourcery. However, type hints serve the purpose of annotating types so that they need not be inferred all the time. I see that mypy can infer this type which is nice. However, PyCharm does not infer the type in this case:

![sourcery_random_integer_inlining](https://user-images.githubusercontent.com/11575/145194999-43059c6f-fe95-4145-af9e-2adbf8c7b193.png)

I know these limitations of my tools and have thus made it a policy to annotate types whenever possible. Sourcery proposes here that I drop a bit of type information that one of my other tools needs.

Also there is a loss of documentation with the local name `random_integer`, which gets returned in the last line of the function named `get_random_integer`. I made it a policy to always `return <something>` in functions that are called `get_<something>`. - And also name functions `get_<something>` when they end in `return <something>`. This enables quick sanity checking whether the programmer has lost their track during writing of the function.

Regards,
Bengt

**Comment by Bengt** [comment]
This issue persists and is widespread in my code bases.

My workaround is to disable this warning like so:

![disable_sourcery](https://user-images.githubusercontent.com/11575/147253461-0f629c38-d7e3-4b7d-930a-9e839b5e93c9.png)
