### ISSUE TITLE
GLIBC_2.18 not found

### ISSUE THREAD

**Issue by eleqtrizit** [sourcery-ai/sourcery#175]
### Issue description or question
ImportError: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by /home/user/.vscode-server/extensions/sourcery.sourcery-0.9.7/sourcery_binaries/install/linux/cryptography/hazmat/bindings/_rust.so)

Sourcery crashes five time and then VSCode renders it inactive.  Recent issue.

### Sourcery Version
v0.9.7

Often available in Sourcery settings

### Code editor or IDE name and version

vscode

### OS name and version

CentOS Linux release 7.9.2009 (Core)

**Comment by brendanator** [comment]
We recently updated the version of cryptography that Sourcery uses. Cryptography now include rust bindings which created this issue.

The next version of Sourcery will fix this issue by including a manylinux2010 compiled version of cryptography

See also https://github.com/sourcery-ai/sourcery-vscode/issues/52

**Comment by Hellebore** [comment]
Should now be fixed with version 0.9.8
