### ISSUE TITLE
How sourcery is analysing the working memory?

### ISSUE THREAD

**Issue by Agent-Hellboy** [sourcery-ai/sourcery#176]
### Sourcery Version

latest

### Code editor or IDE name and version

Vs-Code

### OS name and version

Linux

Is it based on the number of LOAD_* and STORE_* opcode inside a function?

**Comment by Hellebore** [comment]
Hi - it's actually the working memory of the developer rather than the program - see our blog post here:

https://sourcery.ai/blog/working-memory/
