### ISSUE TITLE
Documentation regarding `auth.yaml` file

### ISSUE THREAD

**Issue by Uzaaft** [sourcery-ai/sourcery#177]
### Issue description or question
I have observed that sourcery creates an `auth.yaml` file in the  `~/.config/sourcery/` directory, but it has not been documented in the docs. Could you guys implement it, so that LSP developers knows the expected behaviour of sourcery on all platforms?

### Sourcery Version

version 0.9.8

### Code editor or IDE name and version

NVIM v0.7.0-dev+921-g1907a9481

### OS name and version
I've tested the auth.yaml file on these platforms:

OSX
Linux

**Comment by Hellebore** [comment]
Great idea - thanks for raising. We definitely need better docs on this!

**Comment by Uzaaft** [comment]
Relevant draft PR where we would like to iron this out : https://github.com/neovim/nvim-lspconfig/pull/1495

**Comment by Uzaaft** [comment]
@Hellebore Do you have a timeline for when this will be documented?

**Comment by brendanator** [comment]
Hi @Uzaaft, sorry for the long delay on this one.

We've decided that `auth.yaml` is an implementation detail and we're not going to document it.

Instead, the way to populate this correctly is:
- Install the CLI with `pip install sourcery-cli`
- Run `sourcery login`

This will work correctly on all platforms
