### ISSUE TITLE
Refactoring undoes Unicode CLDR in strings

### ISSUE THREAD

**Issue by diceroll123** [sourcery-ai/sourcery#178]
### Issue description or question
It's probably just easier with a screenshot. (unnecessary code blurred)

I may just be opinionated on this, but I think evaluating the Unicode is a reach. It's probably unintended. 😅

![image](https://user-images.githubusercontent.com/1243957/147395838-df20fc70-795b-42a4-94aa-d22cf03c8112.png)

### Sourcery Version

v0.9.8

### Code editor or IDE name and version

VSCode 1.63.2

### OS name and version

Windows 11 Insider

**Comment by Hellebore** [comment]
Hmm yes this is unintended.

**Comment by diceroll123** [comment]
To add to this, the refactored code doesn't keep the same kind of quotations. Untested with triple quotes.

**Comment by Hellebore** [comment]
Released with 0.10.3
