### ISSUE TITLE
Bug: Wrong suggestion in simplify-fstring-formatting

### ISSUE THREAD

**Issue by minerop5000** [sourcery-ai/sourcery#179]
### Issue description or question
Changes change the result from the code.

Function Browser.handle_mission_array refactored with the following changes:
Simplify unnecessary nesting, casting and constant values in f-strings(simplify-fstring-formatting)

suggestion from sourcery:
  - remove:
  myPrint(f"{f' {i + 1} von {len(mission_array_to_handle)} ':#^25}")
  - add:
  myPrint(f' {i + 1} von {len(mission_array_to_handle)} '

Problem:
:#^25 is totaly ignored
### Sourcery Version
0.9.8

### Code editor or IDE name and version
Pycharm v 2021.2 Professional Edition

### OS name and version
Windows

**Comment by reka** [comment]
Sorry, this is a bug indeed. I was able to reproduce it.
We'll let you know as soon as we've fixed it.

**Comment by reka** [comment]
Hi @minerop5000 ,

We've implemented a fix for this :bug: .
It will be included:

* in the next beta version tomorrow (2021-12-31) in the morning
* in the next release 0.9.9 (Sorry, I don't know when this will be released.)

Thanks a lot for reporting this bug. :+1: 
Please let us know if you find further such issues.

**Comment by Hellebore** [comment]
Fixed in 0.10.0
