### ISSUE TITLE
Unable to connect to Sourcery executable - Pycharm

### ISSUE THREAD

**Issue by lanthos** [sourcery-ai/sourcery#185]
### Issue description or question
Using Pycharm I'm getting a notification in the event log every minute of "Unable to connect to Sourcery executable".  There are no error messages associated with it, so I'm not sure how to grab more information but would be happy to provide more if there's a way.  Using the plugin via VSCode everything is working as expected.  This happened yesterday and I rebooted my computer and the issue went away but has come up again just now.  I've tried uninstalling and re-installing the plugin to no avail as well.

### Sourcery Version
Version 0.10.0

### Code editor or IDE name and version
Pycharm 2021.3.1 Professional Edition, Build #PY-213.6461.77

### OS name and version
macOS Big Sur, Version 11.6.2.  Mac Mini M1, 2020 edition.

If there's any other information that I can provide please let me know!

**Comment by lanthos** [comment]
Information has been sent over (I referenced the issue number here in the subject).  Let me know if there's anything else I can provide!

**Comment by Hellebore** [comment]
Has the error log been happening with previous Sourcery versions as well?

Also is it making suggestions or not working at all?

**Comment by lanthos** [comment]
This is a new thing and just started happening the other day.  I'm pretty sure that the version I'm using is older than that but I can't say for 100% certain.  And no, suggestions aren't working at all.

**Comment by lanthos** [comment]
I should note that it's not providing NEW suggestions.  But suggestions that it had previously found that I haven't used yet, are still showing up and it would work to change them.

**Comment by Hellebore** [comment]
Thanks! Are there any particularly long scripts or functions that you're consistently looking at? 

I think our analysis is timing out, which I'm looking into fixing.

**Comment by lanthos** [comment]
yes indeed!  The project I spend most of my time in is pretty old and there are most certainly some things that need to be refactored badly, once I get some free time.  One in particular has this score if that helps (I think it's the worst of the bunch but there are a few large ones for sure): 

Complexity 
63 
(very poor)  
Refactor to reduce nesting
Size 
471 
(very poor)  
Try splitting into smaller methods
Working Memory 
13 
(poor)  
Extract out complex expressions
Quality Score
13%
(very poor)

**Comment by lanthos** [comment]
It does appear to be limited to that project.  I've opened another project at the same time in a different window and Sourcery is working fine on that one.

**Comment by Hellebore** [comment]
OK - hopefully this should be fixed in the next release.

**Comment by Hellebore** [comment]
@lanthos This should now be addressed with 0.10.1 - please let me know if it isn't!
