### ISSUE TITLE
Replace unneeded comprehension - breaks async for "iterator to list"

### ISSUE THREAD

**Issue by bkcsfi** [sourcery-ai/sourcery#187]
### Issue description or question

I have an async iterator function whose results I want to collect into a list.

Sourcery suggests this change:

![image](https://user-images.githubusercontent.com/6412502/152563872-6f772753-d4a5-46bb-be4f-6443aae8ee3f.png)

Applying the suggested change breaks the code.

Perhaps my solution is not correct, but Sourcery's suggestion is also wrong.

### Sourcery Version

v0.10.1

### Python Version

3.9.9

### Code editor or IDE name and version

vscode insiders

### OS name and version

remote  Ubuntu 20 in a dev container 

Sample program before applying suggestion

```python
"""sample sourcery problem"""
from typing import Iterator


async def get_stuff() -> Iterator[int]:
    """sample function"""
    for i in range(5):
        yield i


async def collect_data():
    """sample function"""
    data = list([_ async for _ in get_stuff()])


import asyncio

asyncio.run(collect_data())
```

after applying suggested refactoring

```python
async def collect_data():
    """sample function"""
    data = list(get_stuff())
```
code doesn't run now

```python
  File "/workspace/manifestserver2/util/test.py", line 13, in collect_data
    data = list(get_stuff())
TypeError: 'async_generator' object is not iterable
```

**Comment by Hellebore** [comment]
Fixed with 0.10.2
