### ISSUE TITLE
Remove extraneous variable during refactor

### ISSUE THREAD

**Issue by diceroll123** [sourcery-ai/sourcery#188]
### Issue description or question

If the variable is only used for the conditional, and unused after factoring, it could be removed in this scenario. This is a design opinion best left to the sourcery devs, I suppose.

![image](https://user-images.githubusercontent.com/1243957/152627038-b68b01e3-5ea8-402d-86c0-c91248ab581d.png)

### Sourcery Version

0.10.1

### Code editor or IDE name and version

Version: 1.64.0 (user setup)
Commit: 5554b12acf27056905806867f251c859323ff7e9
Date: 2022-02-03T04:22:20.678Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22543

**Comment by Hellebore** [comment]
Hmm, yes I think this is probably something we should do.
