### ISSUE TITLE
Pro context menu features (Scan for Refactorings + Detect Clones) not doing anything in VSCode + WSL

### ISSUE THREAD

**Issue by diceroll123** [sourcery-ai/sourcery#190]
### Issue description or question

Similar to #151 except for WSL. Can't seem to find any errors being output...

(Works fine when I switch to Windows mode.)

### Sourcery Version

v0.10.2

### Code editor or IDE name and version

Version: 1.64.1 (user setup)
Commit: d6ee99e4c045a6716e5c653d7da8e9ae6f5a8b03
Date: 2022-02-07T17:16:22.147Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22543

### OS name and version

Windows 11

**Comment by bm424** [comment]
Hi @diceroll123, thanks for reporting this. There's a fix in place for #151 coming out in the next release, I'm tentatively hopeful it will also fix your issue here.

**Comment by Hellebore** [comment]
Should be fixed with release of 0.11.1 - please let us know if it isnt!
