### ISSUE TITLE
Non-integer code metric

### ISSUE THREAD

**Issue by CsatiZoltan** [sourcery-ai/sourcery#192]
### Issue description or question

This is the first time I noticed a non-integer score (code metric). Is it intentional?

![code_metric](https://user-images.githubusercontent.com/12742890/153724170-1e18f997-087f-4c90-834a-9ccae4428d39.png)

### Sourcery Version

0.10.2

### Code editor or IDE name and version

Pycharm 2021.2 (Community Edition)

### OS name and version

Ubuntu 18.04

**Comment by brendanator** [comment]
Thanks for reporting this @CsatiZoltan 🙏

This is not intentional, I will investigate it

**Comment by brendanator** [comment]
This will be resolved in the next release
