### ISSUE TITLE
Sourcery failing to start on ArchLinux 5.16.10-arch1-1

### ISSUE THREAD

**Issue by Hellebore** [sourcery-ai/sourcery#196]
### Issue description or question

I also have almost a similar issue:
java.util.concurrent.ExecutionException: org.eclipse.lsp4j.jsonrpc.JsonRpcException: java.io.IOException: Stream closed Please retry using the refresh button.
Looks like that the service was broken after some updates on my PC but I don't know exactly: I was updating PyCharm, plugins and OS at the same time =(
I was trying to downgrade PyCharm to version 2021.2.2, and Sourcery to version 0.10.1 but without success.

Sourcery Version
Sourcery 0.10.2

IDE name and version
Pycharm 2021.3.2 Professional Edition

OS name and version
ArchLinux 5.16.10-arch1-1

**Comment by Hellebore** [comment]
@NoPH8 Have moved your issue here - could you see if there's a sourcery.log file you could send over to support@sourcery.ai? How to find it is here:
https://docs.sourcery.ai/Resources/Troubleshooting/

**Comment by NoPH8** [comment]
Thanks, done.

**Comment by Hellebore** [comment]
Thanks for sending the log, but unfortunately can't tell what's going on from it.

Am going to mark this as an enhancement for now since we don't actively support Arch.

**Comment by javierriveracastro** [comment]
It looks like Sourcery now uses a legacy version of libxcrypt.

You need to install libxcrypt-compat: `pacman -S libxcrypt-compat`

**Comment by NoPH8** [comment]
You are completely right. Everything works now, thanks!

**Comment by skjongithub** [comment]
> It looks like Sourcery now uses a legacy version of libxcrypt.
> 
> You need to install libxcrypt-compat: `pacman -S libxcrypt-compat`

Fantastic! How did you figure it out?

**Comment by Hellebore** [comment]
Thanks so much @javierriveracastro !!

**Comment by javierriveracastro** [comment]
Have you tried 'libcryp1', without x. In newer releases it contains that lib:

https://packages.ubuntu.com/kinetic/libcrypt1
