### ISSUE TITLE
refactoring can change the value of strings (fstring formatting)

### ISSUE THREAD

**Issue by ReinhardtJ** [sourcery-ai/sourcery#197]
### Issue description or question

I'm currently writing a parser for a certain file format by using regexes. This is my code
```python
tag_pattern = r':([0-9]{2}[A-Z]):'
qualifier_pattern = r':([A-Z]{4})\/\/'
tag_and_qualifier_pattern = f'{tag_pattern}{qualifier_pattern}'
```
on the line with `qualifier_pattern`, it suggests me 
- Inline variable that is only used once(inline-variable)
- Simplify unnecessary nesting, casting and constant values in f-strings(simplify-fstring-formatting)

As soon as I apply, the code becomes
```python
tag_pattern = r':([0-9]{2}[A-Z]):'
tag_and_qualifier_pattern = f'{tag_pattern}:([A-Z]{4})\\/\\/'
```

Firstly, the curly braces around the `4` won't appear in the string anymore, secondly, it adds additional escape-backslashes in front of the already existing backslashes (probably beacuse it detects that `qualifier_pattern` is an r-string. I usually use r-strings for regex-patterns to prevent accidental string formatting, even if it is not needed in this example. Ideally, it shouldn't matter of course).

### Sourcery Version

0.10.1.

### Code editor or IDE name and version

Pycharm 2021.3.1

### OS name and version

Windows

**Comment by Hellebore** [comment]
Thanks for raising - have reproduced the issue and will look into a fix.
