### ISSUE TITLE
pycharm plugin doesnt work on m1 macbook

### ISSUE THREAD

**Issue by paul1995tu** [sourcery-ai/sourcery#203]
### Issue description or question 
Support/JetBrains/PyCharm2021.3/plugins/sourcery/sourcery_binaries/install/mac"): error=86, Bad CPU type in executable Please retry using the refresh button.
### Sourcery Version
newest Version
Often available in Sourcery settings

### Code editor or IDE name and version

Pycharm v?

### OS name and version

Windows
OSX
Linux

**Comment by Hellebore** [comment]
We don't have an M1-native binary but it should work with Rosetta - could you try installing rosetta with the following command and then retrying?

/usr/sbin/softwareupdate --install-rosetta --agree-to-license

**Comment by paul1995tu** [comment]
it worked :)
 

Gesendet: Dienstag, 08. März 2022 um 10:09 Uhr
Von: "Nick Thapen" ***@***.***>
An: "sourcery-ai/sourcery" ***@***.***>
Cc: "paul1995tu" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [sourcery-ai/sourcery] pycharm plugin doesnt work on m1 macbook (Issue #203)


 

We don't have an M1-native binary but it should work with Rosetta - could you try installing rosetta with the following command and then retrying?

/usr/sbin/softwareupdate --install-rosetta --agree-to-license
