### ISSUE TITLE
Unable to connect to Sourcery executable: Object of type PosixPath is not JSON serializable

### ISSUE THREAD

**Issue by danchamorro** [sourcery-ai/sourcery#206]
### Issue description or question
Unable to connect to Sourcery executable: Object of type PosixPath is not JSON serializable

### Sourcery Version

Often available in Sourcery settings
[0.10.3] - 2022-02-24

### Code editor or IDE name and version

Pycharm v?
2021.3.2 

### OS name and version

OSX Monterey 12.3

**Comment by reka** [comment]
Hi,

Thanks a lot for reporting this issue. :+1: 
We're looking into it this is definitely a bug. :bug: 

I was surprised to see that you experienced this issue with the version 0.10.3
We observed the same problem with our new release 0.11.0, but haven't seen it with 0.10.3 yet.
Can you perhaps double-check the Sourcery version number?
Thanks in advance.

Cheers,
Reka

**Comment by Hellebore** [comment]
We have pulled release 0.11.0 - if you uninstall Sourcery and reinstall it should get 0.10.3 again which we think should work correctly. 

We have also identified a fix for the issue which we will shortly release as 0.11.1
