### ISSUE TITLE
Unable to connect to Sourcery executable

### ISSUE THREAD

**Issue by desmith** [sourcery-ai/sourcery#207]
### Issue description or question
After updating the Sourcery plugin to 0.11.0 I get the error:

Unable to connect to Sourcery executable: Object of type PosixPath is not JSON **serializable**

### Sourcery Version

0.11.0

### Code editor or IDE name and version

PyCharm 2021.3.2 (Professional Edition)

### OS name and version
macOS Monterey 12.3

MacBook Pro (Retina, 15-inch, Mid 2015)
Processor: 2.5 GHz Quad-Core Intel Core i7
Memory: 16 GB 1600 MHz DDR3

**Comment by desmith** [comment]
MacBook Pro (Retina, 15-inch, Mid 2015)
Processor: 2.5 GHz Quad-Core Intel Core i7
Memory: 16 GB 1600 MHz DDR3

**Comment by Hellebore** [comment]
Thanks for reporting this! This is an issue with release 0.11.0, which we have now pulled from the marketplace - if you uninstall Sourcery and reinstall it should get 0.10.3 again which we think should work correctly.

We have also identified a fix for the issue which we will shortly release as 0.11.1

**Comment by desmith** [comment]
Reverting to 0.10.3 working as promised - thanks!
