### ISSUE TITLE
PyCharm plugin cannot connect

### ISSUE THREAD

**Issue by GavinHuttley** [sourcery-ai/sourcery#209]
### Issue description or question

"10:49 am	Unable to connect to Sourcery executable: Object of type PosixPath is not JSON serializable"

### Sourcery Version

0.11.0

### Code editor or IDE name and version

Pycharm v?
PyCharm 2021.3.2 (Professional Edition)
Build #PY-213.6777.50, built on January 28, 2022

### OS name and version

OSX 12.3

**Comment by reka** [comment]
Thanks for reporting this! This is a bug :bug:  in release 0.11.0
For this reason, we have pulled 0.11.0 from the marketplace. If you uninstall Sourcery and reinstall it, you should get 0.10.3 which we think should work correctly. Let us know if you experience any issues with that.

We'll also release 0.11.1 soon

**Comment by Hellebore** [comment]
0.11.1 now released.
