### ISSUE TITLE
Refactoring of a nested function

### ISSUE THREAD

**Issue by ergleb78** [sourcery-ai/sourcery#212]
### Issue description or question
Refactoring of a nested function causes incorrect results:

```
def func1():
    return "Useless value"


def foo():
    def bar():
        if func1():
            pass
            pass
            return
        else:
            raise KeyError

    for i in range(5):
        print("Doing something useless")
        bar()

```
suggested refactoring: Remove redundant pass statement(remove-redundant-pass)

the result after refactoring:

```
def func1():
    return "Useless value"


def bar():
        if func1():
            return
        else:
            raise KeyError

``` 

It looks like it pulls a function one level up, removes nested function but keeps spacing. I didn't test it in different conditions but it seems to be independent of a kind of suggested refactoring. 

 
### Sourcery Version
0.10.2

### Code editor or IDE name and version

Pycharm v?
2021.2.3 Community

### OS name and version

OSX

**Comment by Hellebore** [comment]
Thanks for raising - this has been addressed in the latest version of Sourcery for PyCharm (0.11.1) - could you please upgrade your plugin version and give it another try?
