### ISSUE TITLE
Refactoring f strings and escaped chars in strings

### ISSUE THREAD

**Issue by oserban** [sourcery-ai/sourcery#213]
### Issue description or question

When having f strings without any substitutions sourcery recommends converting into string. While the suggestion is good, the resulting conversion is not always good, especially if you are using escaped chars in strings:

Example:

```python
print(f"Hello\tworld")
```

will result into after conversion:

```python
print("Hello\\tworld")
```

### Sourcery Version

0.11.1

### Code editor or IDE name and version

Pycharm 2021.3.3

### OS name and version

OSX

**Comment by Hellebore** [comment]
Thanks for raising - definitely an issue!

**Comment by bm424** [comment]
@oserban This issue shouldn't arise as of the next release of Sourcery (11.3). Let us know if it persists after that!
