### ISSUE TITLE
Suggested refactoring causes mypy linting error

### ISSUE THREAD

**Issue by dimitri-b** [sourcery-ai/sourcery#218]
### Issue description or question
Given this original code:
```python
        # sourcery skip: remove-unnecessary-else, swap-if-else-branches, use-named-expression
        table_id_pattern = re.compile(r"^([\w\-]+)(?:\.|\:)(\w+)\.\w+$")
        matching_groups = re.fullmatch(table_id_pattern, destination_table_name)
        if matching_groups:
            project_id = matching_groups.group(1)
            dataset_id = matching_groups.group(2)
        else:
            raise ValueError(f"Invalid value for table ID: {destination_table_name}")
```
the suggested refactoring, if done, will obfuscate from mypy the check for Null value, causing mypy to flag an issue on linting.
Details: `re.fullmatch` (and other methods) may return None if no match is found. If a named expression is used, as suggested, then mypy will complain that `None` doesn't have `.group` attribute.

### Sourcery Version

0.11.1

### Code editor or IDE name and version

PyCharm 2021.3.3 (Pro)

### OS name and version

OSX 11.6.2

**Comment by bm424** [comment]
Hi @dimitri-b, thanks for raising this! I've not been able to reproduce the issue. Using your code like so:

```python
import re

destination_table_name = "foo"

table_id_pattern = re.compile(r"^([\w\-]+)(?:\.|\:)(\w+)\.\w+$")
matching_groups = re.fullmatch(table_id_pattern, destination_table_name)
if matching_groups:
    project_id = matching_groups.group(1)
    dataset_id = matching_groups.group(2)
else:
    raise ValueError(f"Invalid value for table ID: {destination_table_name}")
```
I get the following refactoring using Sourcery:
```python
import re

destination_table_name = "foo"

table_id_pattern = re.compile(r"^([\w\-]+)(?:\.|\:)(\w+)\.\w+$")
if not (
    matching_groups := re.fullmatch(table_id_pattern, destination_table_name)
):
    raise ValueError(f"Invalid value for table ID: {destination_table_name}")
project_id = matching_groups.group(1)
dataset_id = matching_groups.group(2)
```
With the new code, I don't get any Mypy errors (mypy version 0.931). Could you confirm you're getting the same refactoring, and which version of Mypy you're using? Thanks!

**Comment by dimitri-b** [comment]
Weird, I just tried it myself again, and Mypy no longer complains.
I use v0.812.
Not sure what it was.

**Comment by dimitri-b** [comment]
Cannot reproduce, possibly due to Sourcery update since the issue was detected.
