### ISSUE TITLE
Refactoring instance-method-first-arg-name not compatible with Pydantic validator decorator

### ISSUE THREAD

**Issue by JPMarais-Inscorep** [sourcery-ai/sourcery#219]
### Issue description or question

When using Pydantic to validate data models, Soucery notes that a **instance-method-frist-arg-name** refactoring is required for a Pydantic validator method. Although the method is not decorated with the `@classmethod` decorator, the Pydantic `@validator` decorator returns a class method and as such the code sample below should not require a refactoring:

```python
from pydantic import BaseModel, validator

class TestModel(BaseModel):
    name: str
    age: int

    @validator(age)
    def validator_age(cls, v: int) -> int:
        if v < 0:
            raise ValueError("Age must be positive")
        return v
```

As noted in the Pydantic [repo](https://github.com/samuelcolvin/pydantic/issues/1415), Pydantic is probably not following the PEP8 guideline of explicit is better than implicit, but would it be possible to allow for this in Sourcery so that the specific refactoring does not need to be switched off for the whole project?

### Sourcery Version

v0.11.2

### Code editor or IDE name and version

VSCode v1.66

### OS name and version

Windows 11 Pro 21H2

**Comment by Hellebore** [comment]
Fixed in 0.11.3
