### ISSUE TITLE
Remove `You've skipped a refactoring, help us improve it.` popup?

### ISSUE THREAD

**Issue by diceroll123** [sourcery-ai/sourcery#229]
### Issue description or question

The `You've skipped a refactoring, help us improve it.` popup has the word `improve` link to a now-defunct Typeform url.

![image](https://user-images.githubusercontent.com/1243957/163909468-d89a76c8-75f2-4295-b6d4-63d497b67f9e.png)
![image](https://user-images.githubusercontent.com/1243957/163909503-c03e9545-638c-4efd-a4ea-c17a06cfa148.png)

### Sourcery Version

v0.11.2

**Comment by reka** [comment]
Hi @diceroll123 ,

Thanks a lot for reporting this bug. :bug: 
We're looking into it. For now, I have 2 questions:

* Which refactoring did you skip?
* Do I see correctly that you were using the VSCode Sourcery extension?

Thanks for the info in advance.

Cheers,
Reka

**Comment by reka** [comment]
Sorry, this was an issue with our Typeform quota. It should be fixed now.
Thanks again for reporting this. :smiley:
