### ISSUE TITLE
Sourcery removes comments in some refactors

### ISSUE THREAD

**Issue by rhytnen** [sourcery-ai/sourcery#23]
### Issue description or question
It refactored some code and deleted comments

### Sourcery Version
0.3.0

### Code editor or IDE name and version
Pycharm v2019.3

### OS name and version

Windows 10

Here is my diff.

![image](https://user-images.githubusercontent.com/632888/74179775-f6065380-4bf2-11ea-93da-d9c4bcd89816.png)

**Comment by Hellebore** [comment]
Thanks for raising this. I will look into it.

**Comment by Hellebore** [comment]
This is going to require some re-jigging of how we handle comments.

May take a little bit of time to schedule in.

**Comment by Hellebore** [comment]
Identified a fix for this, should be in next release.

**Comment by Hellebore** [comment]
Resolved with version 0.3.2
