### ISSUE TITLE
Sourcery eating up 12GB of memory... 

### ISSUE THREAD

**Issue by Eagleames** [sourcery-ai/sourcery#230]
### Issue description or question
![image](https://user-images.githubusercontent.com/24260928/164296375-0196a9b5-7970-4dc0-b3d2-d5fb929da6a6.png)

Not sure what happened, only went away when I closed all of my VScode windows...
Clearly got run away eating up tons of memory!!

### Sourcery Version
v0.11.2

### Code editor or IDE name and version

VSCODE 1.66.2
### OS name and version

Windows 10 21H2

**Comment by reka** [comment]
Hi @Eagleames ,
Thanks a lot for reporting this bug.
We're working on a fix for it.

Do you perhaps have some ideas under which circumstances this occurs?
E.g. does it happen for all of your projects or only for some of them?

We'll let you know when we have a fix for this.

Cheers,
Reka

**Comment by Eagleames** [comment]
Howdy!
So, i don't really know what happened.
I can say that at the start of realizing it, i had maybe 6 different projects open.

But then I just told VSCode to close everything and all windows but two closed.

The weirdest thing is that it maintained high memory through the closing of one more window, and then with only a *tiny* project where i was just learning to use mechanicalsoup it didn't go away.
When I closed that instance then sourcery closed itself.

Frankly i don't think that was the cause (but rather that other larger projects somehow got it in a loop or something...

But no way to know.
Only saw it once, but if i catch it again I will repost.

**Comment by WXZhao7** [comment]
It used 6.6Gb memory when I test some simple and short python scripts :(
```shell
> ps -eo size,pid,user,command | grep -i 'sourcery' | grep -v 'grep' | awk '{ hr=$1/1024 ; printf("%.2fMB\t%s",hr,$4)}'
7017.96MB	/home/wxz/.vscode/extensions/sourcery.sourcery-0.11.4/sourcery_binaries/install/linux/sourcery
```

**Comment by bm424** [comment]
Hey @Eagleames and @WXZhao7 - thanks for providing some context on this. We made a couple of tweaks in Sourcery 0.11.5 (released 2022-05-18) to reduce the memory footprint. I was wondering if you've noticed any improvement?

**Comment by WXZhao7** [comment]
@bm424 Yeah, it only cost around 500mb now. Thanks for your support :)

**Comment by bm424** [comment]
That's great, glad to hear it's working better for you. I'm going to close this issue for now, but feel free to get in touch again.
