### ISSUE TITLE
VSCode extension applies `.sourcery.yaml` found in the first folder of a multi-root workspace to all roots

### ISSUE THREAD

**Issue by blakeNaccarato** [sourcery-ai/sourcery#231]
### Issue description or question

The VSCode extension only respects `.sourcery.yaml` in the first path defined in the `*.code-workspace` file for a multi-root workspace. It then proceeds to apply this configuration to all folder roots in that multi-root workspace. This leads to unexpected behavior where the desired configuration "leaks" to potentially-unrelated project roots. If no `.sourcery.yaml` exists in the first path defined in the `*.code-workspace` config, then no `.sourcery.yaml` is loaded even if there are some in lower folders in the config.

Instead, Sourcery should only apply `.sourcery.yaml` configs to the root in which this file is found. If a given folder has no `.sourcery.yaml`, then it should not leak configs from other roots.

### Sourcery Version

v0.11.2

### Code editor or IDE name and version

VSCode 

v1.66.2

### OS name and version

Windows 10

**Comment by reka** [comment]
Hi @blakeNaccarato ,

Thanks a lot for reporting this bug :bug: .
We're looking into it and we'll let you know when there's some update.

Cheers,
Reka
