### ISSUE TITLE
Sourcery doesn't seem to refactor functions in functions

### ISSUE THREAD

**Issue by rhytnen** [sourcery-ai/sourcery#24]
### Issue description or question
Code that sourcery would recactor is ignored if defined as a function inside another function

### Sourcery Version
0
.3.0

### Code editor or IDE name and version

Pycharm v2019.3

### OS name and version

Windows 10

Here is a bit of a contrived example

![image](https://user-images.githubusercontent.com/632888/74179962-585f5400-4bf3-11ea-80ac-d2de8e11d38c.png)

![image](https://user-images.githubusercontent.com/632888/74180016-7af16d00-4bf3-11ea-94ca-5c39de916344.png)

**Comment by Hellebore** [comment]
At the moment our analysis of variable usage in and around nested functions isn't complete, so we've disabled Sourcery for nested functions.

This is on our roadmap to address, but might take a little bit of time.

**Comment by Hellebore** [comment]
This should now work.
