### ISSUE TITLE
Suggestion removes virtually all functionality of code block.

### ISSUE THREAD

**Issue by beofhelp** [sourcery-ai/sourcery#241]
### Suggestion removes virtually all functionality of code block.

![image](https://user-images.githubusercontent.com/17787716/169638444-b8ba397d-e0d5-4f7d-bda8-9ba2ef7ee640.png)

### Sourcery Version

0.11.5

### Code editor or IDE name and version

PyCharm 2021.2.3 (Community Edition)

### OS name and version

Windows 10.0.19044

**Comment by Hellebore** [comment]
Hi @beofhelp - is it possible for you to post the 'before' code as text? That will make it much easier for us to reproduce the issue. Thanks!

**Comment by ruancomelli** [comment]
Hi again, @beofhelp! This just merged a fix for this issue - it will be out in the next Sourcery release. Thanks for bringing this up!

**Comment by Hellebore** [comment]
Fixed with 0.12.0
