### ISSUE TITLE
Sourcery is chewing up a lot of CPU despite my IDE not actually being open.

### ISSUE THREAD

**Issue by anotherstarburst** [sourcery-ai/sourcery#242]
### Issue description or question

Sourcery is chewing up a lot of CPU despite my IDE not actually being open. My IDE hasn't been open for hours.

![Screenshot 2022-05-21 at 11 37 59](https://user-images.githubusercontent.com/484487/169648049-870e6984-a268-487d-8a03-4d581adbd4a1.png)

### Sourcery Version

v0.11.5

### Code editor or IDE name and version

VS Code Version: 1.67.2

### OS name and version

OSX v11.6.5

**Comment by Hellebore** [comment]
Closing as stale.
