### ISSUE TITLE
key/value pair not being wrapped in parentheses with itertools.product refactorig

### ISSUE THREAD

**Issue by angrycaptain19** [sourcery-ai/sourcery#248]
Sourcery suggested a nifty Python refactoring to move from nested for loops to using itertools.product

The bug is that the 2nd set of key/values should also be wrapped in parentheses like domain_key and domain_v are. When doing the refactoring those were left out and caused an error.

![unnamed (9)](https://user-images.githubusercontent.com/53473467/172127966-704d57df-47ec-4296-82c1-f4049c27eeca.png)

**Comment by bm424** [comment]
@Hellebore can you confirm this will be resolved in the next release?

**Comment by Hellebore** [comment]
Resolved with release of 0.12.1
