### ISSUE TITLE
Unable to Install Sourcery-cli

### ISSUE THREAD

**Issue by destroyace** [sourcery-ai/sourcery#257]
### Issue description or question
I am unable to install sourcery-cli via pip. When I run `pip install sourcery-cli`, I am shown the following error:
```
$ pip install sourcery-cli
ERROR: Could not find a version that satisfies the requirement sourcery-cli (from versions: none)
ERROR: No matching distribution found for sourcery-cli
```

### Sourcery Version
N/A

### Code editor or IDE name and version
Attempting to install it for Sublime, my ST version is 4 (build 4126)

### OS name and version
Windows 11 21H2

**Comment by ruancomelli** [comment]
Hello, @destroyace, thanks for reaching out!

What pip and Python versions are you using? You can check both by running `pip --version` and `python --version`.

**Comment by destroyace** [comment]
Hi, thanks for the quick response! 
```
$ pip --version
pip 22.2 from c:\users\user\appdata\local\programs\python\python39-32\lib\site-packages\pip (python 3.9)
```
and 
```
$ python --version
Python 3.9.0
```

**Comment by ruancomelli** [comment]
I suspect that you are running a 32-bit version of Python? Currently, [we only support 64-bit](https://pypi.org/project/sourcery-cli/#files).

Are you using a 32-bit machine? If not, could you please try [installing Python 64-bit](https://www.python.org/downloads/windows/) and checking if `pip install sourcery-cli` works?

**Comment by Hellebore** [comment]
Hi @destroyace - closing this for now - do let us know if the problem wasn't the lack of 32 bit support.

**Comment by destroyace** [comment]
Hi, yes it was. Thank you!
