### ISSUE TITLE
Error is raised in `match` statements in Python 3.10

### ISSUE THREAD

**Issue by ruancomelli** [sourcery-ai/sourcery#258]
### Issue description or question

**Issue reported to our e-mail support.**

The `match` statement, introduced in Python 3.10, causes Sourcery to throw the following error:

```
[Error - 6:28:41 PM] Request textDocument/hover failed.

  Message: File "<unknown>", line 2

    match separation_type:

IndentationError: unexpected indent

  Code: -32602

[object Object]
```

### Sourcery Version

0.12.3

### Code editor or IDE name and version

VS Code 1.69.2

### OS name and version

Ubuntu, connected to via SSH from MacOS

**Comment by Hellebore** [comment]
There's quite a lot to do here:
- Create nodes for the new syntax
- Make sure these parse and unparse
- Enhance our analysis so that they are handled correctly
  - control flow
  - node dependencies
  - probably a bunch of other stuff

**Comment by Hellebore** [comment]
Fixed.
