### ISSUE TITLE
Refactored conditionals aren't optimal

### ISSUE THREAD

**Issue by rhytnen** [sourcery-ai/sourcery#26]
### Issue description or question
Some refactors of If / Else blocks seem non-optimal

### Sourcery Version
0.3.0

Often available in Sourcery settings

### Code editor or IDE name and version

Pycharm v2019.3

### OS name and version

Windows 10

![image](https://user-images.githubusercontent.com/632888/74291481-d1d96e00-4ce9-11ea-9cc3-a83a475671f5.png)

will refactor to

![image](https://user-images.githubusercontent.com/632888/74291520-ee75a600-4ce9-11ea-8a84-8a8e7a3b318f.png)

but i feel like it should refactor to

![image](https://user-images.githubusercontent.com/632888/74291542-00574900-4cea-11ea-8e4e-e7273375c74b.png)

**Comment by Hellebore** [comment]
You're right - we should be refactoring it as you say. Will investigate.

**Comment by Hellebore** [comment]
Addressed the issue - the fix should be in our next release.

**Comment by Hellebore** [comment]
Fixed with plugin version 0.3.1
