### ISSUE TITLE
JSON schema files for project and user settings?

### ISSUE THREAD

**Issue by willfrey** [sourcery-ai/sourcery#263]
### Issue description or question

Could you provide JSON schema files for your project and user settings? This would make changing (and exploring) the settings options available right from an IDE/editor, as many have features that rely on having a schema for the file.

### Sourcery Version

v0.12.6

### Code editor or IDE name and version

VS Code 1.70.0

### OS name and version

macOS 12.5

**Comment by brendanator** [comment]
This is a great idea @willfrey! 

We'll look into it

**Comment by Hellebore** [comment]
We now have a schema!
https://docs.sourcery.ai/Guides/IDE-Autocompletion/
