### ISSUE TITLE
no such table: jwk 

### ISSUE THREAD

**Issue by tekumara** [sourcery-ai/sourcery#267]
### Issue description or question

Just after install I get:
```
(sqlite3.OperationalError) no such table: jwk [SQL: SELECT count(*) FROM jwk] (Background on this error at: http://sqlalche.me/e/13/e3q8)
```

### Sourcery Version

v0.12.6

### Code editor or IDE name and version

vscode Version: 1.70.2

### OS name and version

OSX

**Comment by bm424** [comment]
Hi @tekumara, thanks for reporting this issue. Here are a couple of things that can help us solve the problem:

1. We don't officially support Sourcery on Apple computers with an M1 chip, although it may work if you have Rosetta installed (see our documentation [here](https://docs.sourcery.ai/Troubleshooting/#sourcery-not-working-on-apple-m1)).
2. The JWK database is to do with authentication and should have instantiated on start-up. Could you try re-installing, and if it fails again, would you be able to email us your Sourcery log file at hello@sourcery.ai? You can find the log file following the instructions [here](https://docs.sourcery.ai/Troubleshooting/#what-is-the-sourcery-log)
