### ISSUE TITLE
Sourcery wants to hoist comments out of loops

### ISSUE THREAD

**Issue by rhytnen** [sourcery-ai/sourcery#27]
### Issue description or question
Sourcery wants to hoist comments out of loops

### Sourcery Version
0.3.0

Often available in Sourcery settings

### Code editor or IDE name and version

Pycharm v2019.3

### OS name and version

Windows 10

I have noticed that sourcery frequently wants to hoist comments out of loops.  I get entire reformat suggestions that are based on comments being hoisted up.

This doesn't seem like something you actually want.

**Comment by Hellebore** [comment]
You're right - It should only ever hoist comments together with some code. 

Can you give an example so I can reproduce it?

**Comment by rhytnen** [comment]
Here you go:
![image](https://user-images.githubusercontent.com/632888/74464388-4aeed780-4e48-11ea-87f8-abd768825ef4.png)

**Comment by Hellebore** [comment]
Ah I see the problem. Should be quick to fix.

**Comment by Hellebore** [comment]
Fixed - will be in next release.

**Comment by Hellebore** [comment]
Fixed with plugin version 0.3.1
