### ISSUE TITLE
Possible vocabulary improvement

### ISSUE THREAD

**Issue by rhytnen** [sourcery-ai/sourcery#28]
### Issue description or question
Description of some issues doesn't seem right

### Sourcery Version
0.3.0

Often available in Sourcery settings

### Code editor or IDE name and version

Pycharm v2019.3

### OS name and version

Windows 10

A typical example would be:
```Python
def x():
  return 
  print('Unreachable')
```

For me, the message says, "remove redundant code" and it will delete everything under the return.  This isn't redundant code, it's just unreachable and probably represents a mistake.  Deleting it as redundant is certainly a mistake.  

I think the vocabulary should change to unreachable but I am unsure what the correct refactor (if any) should be.

**Comment by Hellebore** [comment]
Fair point on it being unreachable rather than redundant. Will have a think about it.

**Comment by Hellebore** [comment]
Renamed in next release.

**Comment by Hellebore** [comment]
Rename now live with plugin version 0.3.1
