### ISSUE TITLE
Comments aggressively removed in refactoring

### ISSUE THREAD

**Issue by vigilyn** [sourcery-ai/sourcery#280]
### Description

Sourcery should not remove comments.

#### Original code
```python
def some_function(event):
    # league_id is actually stored in event's "id" key and not league_id key
    league_id = event.get("id")
    if league_id:
        res.league_id = league_id
```

#### Sourcery Suggested refactoring (use-named-expression)
```diff
def some_function(event):
-    # league_id is actually stored in event's "id" key and not league_id key
-    league_id = event.get("id")
-    if league_id:
+    if league_id := event.get("id")
        res.league_id = league_id
```

#### Actual Desired refactoring (use-named-expression)
```diff
def some_function(event):
     # league_id is actually stored in event's "id" key and not league_id key
-    league_id = event.get("id")
-    if league_id:
+    if league_id := event.get("id")
        res.league_id = league_id
```

### Debug Information

IDE Version: 
PyCharm 2022.2.1 (Professional Edition)
Build #PY-222.3739.56, built on August 16, 2022
Runtime version: 17.0.3+7-b469.37 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.

Sourcery Version: 
sourcery.pycharm-plugin (0.12.8)

Operating system and Version:
macOS 12.6

**Comment by Hellebore** [comment]
This will be addressed by the new engine.

**Comment by Danie-1** [comment]
In general, inline comments also seem to be removed. For example:
```py
var1 = "World!"
var2 = "Hello {}".format(var1)  # a comment
```
becomes:
```py
var1 = "World!"
var2 = f"Hello {var1}"
```
