### ISSUE TITLE
missing webpage 404

### ISSUE THREAD

**Issue by RincewindLangner** [sourcery-ai/sourcery#283]
Dear all,

There is a 404 page on the website when you go to it from within the pop up box in vscode. The link is 
https://docs.sourcery.ai/refactorings/convert-to-enumerate/

Thanks

**Comment by Hellebore** [comment]
Thanks for raising this! We're fixing these links in our next release.

**Comment by brendanator** [comment]
This is now fixed @RincewindLangner
