### ISSUE TITLE
Can't select individual refactorings when multiple ones are suggested for given code block

### ISSUE THREAD

**Issue by cyril-schroeder-ox** [sourcery-ai/sourcery#285]
### Checklist

- [ x] I have searched the [Sourcery documentation](https://docs.sourcery.ai/) for the issue, and found nothing
- [ x] I have checked there are no open [bugs](https://github.com/sourcery-ai/sourcery/issues?q=label%3Abug) referencing the same bug or problem

### Description
When multiple refactorings for the block of code are suggested, can only implement all of them at the same time, as opposed to being able to select each one individually.

### Debug Information

IDE Version: 
VSCode 1.71.2

Sourcery Version: 
v0.12.9

Operating system and Version:
Ubuntu 22.04

**Comment by bm424** [comment]
Hey @cyril-schroeder-ox, thanks for reporting the issue. Would it be possible for you to share a code snippet illustrating the problem? On the whole what you've described seems to work for me. 

In the screenshot below you can see two lines in the function body highlighted, one to refactor the try/except bit and one to refactor the summation loop. Both can be accepted individually.

![Screenshot from 2022-09-28 09-46-59](https://user-images.githubusercontent.com/15631502/192734097-3279445c-a502-404b-9e64-43e29c28b6cf.png)

**Comment by Hellebore** [comment]
Closing as stale.
