### ISSUE TITLE
`invert-any-all` does not refactor correctly with chained comparison

### ISSUE THREAD

**Issue by randallpittman** [sourcery-ai/sourcery#286]
### Checklist

- [x] I have searched the [Sourcery documentation](https://docs.sourcery.ai/) for the issue, and found nothing
- [x] I have checked there are no open [bugs](https://github.com/sourcery-ai/sourcery/issues?q=label%3Abug) referencing the same bug or problem

### Description

On the following code:

```python
if not all(0 <= v <= 255 for v in v): 
    raise ValueError(...)
```

Sourcery recommends the following change:

```python
if any((0 <= v <= 255 for v in v)): 
   raise ValueError(...)
```

citing the `invert-any-all` rule. It seems that the `invert-any-all` rule does not know how to handle chained comparisons.

This would be an appropriate application of the `invert-any-all` rule (though not an improvement in this case, IMO):

```python
if any(v < 0 or 255 < v for v in v):
    raise ValueError(...)
```

### Debug Information

IDE Version: 
Visual Studio Code 1.71.2

Sourcery Version: 
v0.12.9

Operating system and Version:
Linux Mint 20.3

**Comment by randallpittman** [comment]
Related, the extra parentheses are not needed--`any` and `all` accept the bare comprehension just fine.

**Comment by ruancomelli** [comment]
Hello, @randallpittman, thanks for reporting this issue!

You are correct in all of your three main points:

1. replacing `not all(0 <= v <= 255 for v in v)` with `any((0 <= v <= 255 for v in v))` is just wrong
2. even if Sourcery had suggested the correct change, I agree that `any(v < 0 or 255 < v for v in v)` is not any clearer
3. and yes, Sourcery should not have introduced that extraneous pair of parenthesis

I was able to reproduce it and will work on a fix.

**Comment by ruancomelli** [comment]
Hi again, @randallpittman!

A fix for this issue was just merged and will be available in the next release.

Thank you for reporting it!

**Comment by randallpittman** [comment]
@ruancomelli No problem--thank you for your attention to the issue!

**Comment by Hellebore** [comment]
Now live!
