### ISSUE TITLE
Skip large file

### ISSUE THREAD

**Issue by CoyoteLeo** [sourcery-ai/sourcery#31]
### Skip large file
There are some large files in my project. Result from the above, when sourcery scans these file, it takes lot of time and lot of cpu usage. To figure this problem, I prefer to skip some files that they don't need to be scanned.

### Sourcery Version
Plan: Sourcery Pro.
Plugin version: 0.3.0
Sourcery Version: 0.5.11

### Code editor or IDE name and version
PyCharm 2019.3.3 (Professional Edition)
Build #PY-193.6494.30, built on February 6, 2020

### OS name and version
OSX 10.15.3

**Comment by Hellebore** [comment]
We're working on adding a configuration file that will let you exclude files and directories.

Will keep this issue updated with our progress.

**Comment by Hellebore** [comment]
This can now be configured using the new .sourcery.yaml file documented here:

https://github.com/sourcery-ai/sourcery/wiki/Sourcery-configuration
