### ISSUE TITLE
Variable name `_`  (underscore) triggers avoid-single-character-names-variables.

### ISSUE THREAD

**Issue by gsnidero** [sourcery-ai/sourcery#315]
### Description
A variable named `_`  (underscore) sometimes triggers the "Avoid single character names (avoid-single-character-names-variables)" rule.

### Code snippet that reproduces issue
```python
# here is OK
for _ in range(5):
    print("hello")


def func(number: int) -> int:
    ...

# here triggers "Avoid single character names (avoid-single-character-names-variables)"
_ = func(10)
```

### Debug Information

IDE Version: VSCode Version: 1.74.3 (Universal)
Sourcery Version: v1.0.3
Operating system and Version: Apple M1 Pro, macOS 13.1 (22C65),

**Comment by bm424** [comment]
Hi @gsnidero, thanks for reaching out. The `avoid-single-character-names-variables` rule is based on the Google Python Style Guide, which we're trying to follow closely, and as a result I think this trigger is correct, so I'm going to close this issue. 

If you'd prefer different behaviour, you can disable this rule and instead write your own into your `.sourcery.yaml` config file - the documentation [here](https://docs.sourcery.ai/Tutorials/Custom-Rules/) and the rule definition [here](https://github.com/sourcery-ai/sourcery-rules/blob/main/google-python-style-guide.yaml#L852-L888) should help get you started.

**Comment by gsnidero** [comment]
Hi @bm424, ok – I was thinking at the common use of `_` as a "throwaway variable" [e.g.](https://stackoverflow.com/questions/5893163/what-is-the-purpose-of-the-single-underscore-variable-in-python). Thank you for the quick reply.
