### ISSUE TITLE
How can we remove the Sourcery Quality reports?

### ISSUE THREAD

**Issue by joamatab** [sourcery-ai/sourcery#329]
How can we remove the [Sourcery Quality reports](https://docs.sourcery.ai/Explanation/GitHub/Quality-Report/)

I love sourcery and is great to send PRs to automatically refactor the code, it has improved the quality of my code since I started using it

one issue i find is that the Source quality reports are quite long and discourage PR conversations, see for example

https://github.com/gdsfactory/gdsfactory/pull/1496

**Comment by reka** [comment]
Hey,

Thanks a lot for this useful feedback. :+1:  I can absolutely understand why the quality report feels annoying. :slightly_smiling_face: 

I haven't found a way so far to remove it. We'll probably add this option in the next version.

Cheers,
Reka

**Comment by reka** [comment]
Thanks again for this great suggestion. :+1: 

After some internal discussion, we've removed the Sourcery Code Quality Report from the GitHub bot.
Starting with this morning, you shouldn't see it in your new PRs anymore.

**Comment by joamatab** [comment]
Hi Reka,

great, thank you!
