### ISSUE TITLE
Quick fix action does not appear in last version

### ISSUE THREAD

**Issue by mr-pablinho** [sourcery-ai/sourcery#335]
The "quick fix" button is not popping up in the very last version v1.1.0. Therefore, there is no way to automatically apply the suggested fixes. There is no problem when running v1.0.9.

**Comment by bm424** [comment]
Hi @mr-pablinho - I don't think this is a general bug (see below screenshot of quick-fixes working with Sourcery 1.1.0).

![Screenshot from 2023-04-06 11-39-35](https://user-images.githubusercontent.com/15631502/230355108-d70ddbdc-d8eb-4e62-9518-8bff66bf16f5.png)

Please send a support request to support@sourcery.ai hare which IDE you're using (I assume VSCode?) and which version, which operating system you're on, and a code snippet that you expect to see quick fixes for. Also, if you have any custom Sourcery configuration, please share it. Finally, it would be helpful if you could share your log file (send it to support@sourcery.ai) - instructions can be found [in our docs](https://docs.sourcery.ai/Product/Troubleshooting/#what-is-the-sourcery-log).
