### ISSUE TITLE
Bug when refactoring conditionals with parentheses

### ISSUE THREAD

**Issue by reka** [sourcery-ai/sourcery#346]
Thanks to @quentinsf for reporting this issue.

## Buggy Test Case

> I had some code which looks like this:

```python
if is_codalink:
   if (int(parts[0]) > 1440) or (int(parts[1]) > 1024):
       continue
```

> Sourcery suggested the following refactoring:

```python
if is_codalink and (int(parts[0]) > 1440) or (int(parts[1]) > 1024):
       continue
```

But this is wrong.

> The issue is that the and is more tightly binding than the or, so this is effectively:

```python
if (  is_codalink and (int(parts[0]) > 1440)  ) or (int(parts[1]) > 1024):
       continue
```

## Similar & Correct Test Case

If the original code doesn't contain the parentheses
=>
Sourcery suggests a correct refactoring.

```python
if is_codalink:
   if int(parts[0]) > 1440 or int(parts[1]) > 1024:
       continue
```

=>

```python
if is_codalink and (int(parts[0]) > 1440 or int(parts[1]) > 1024):
   continue
```

**Comment by Hellebore** [comment]
This should now be addressed with the release of 1.3.0
