### ISSUE TITLE
Sourcery failing with permission errors on remote SSH

### ISSUE THREAD

**Issue by Hellebore** [sourcery-ai/sourcery#348]
### Checklist

- [ ] I have searched the [Sourcery documentation](https://docs.sourcery.ai/) for the issue, and found nothing
- [ ] I have checked there are no open [bugs](https://github.com/sourcery-ai/sourcery/issues?q=label%3Abug) referencing the same bug or problem

### Description

When running Sourcery via remote SSH where the user has permissions to their home directory but not its parent, sourcery is failing with permission errors.

This is due to Sourcery attempting to find the project root and recursing too far up the directory structure.

### Code snippet that reproduces issue
N/A

### Debug Information

IDE Version: 
VS Code

Sourcery Version: 
1.3.0

Operating system and Version:
Linux RHE 8.7 with remote SSH

**Comment by ruancomelli** [comment]
@Hellebore, a fix for this issue was just merged and will be available in the next release.
Can you please notify the user you were in contact with?
