### ISSUE TITLE
Simplify comparison to boolean leads to false positive

### ISSUE THREAD

**Issue by angrycaptain19** [sourcery-ai/sourcery#349]
# Given
```
class HasNoneAttr():
  def __init__(self):
        self.returns_none: None = None

instance = HasNoneAttr()
```
# When
`getattr(instance, 'returns_none', False) is False`
# Then
Suggested refactor given
`Sourcery - Simplify comparison to boolean`
`not getattr(instance, 'returns_none', False)`
# Expected
No refactor suggestion
A falsey comparison is not the same as an `is False` comparison.
Using getattr with a default of False allows catching a case where the attr does in-fact exist, but returns None.

**Comment by ruancomelli** [comment]
Fixed in [v1.4.0](https://sourcery.ai/changelog/2023-06-19-2023-06-19/).
