### ISSUE TITLE
Sourcery bot failed to refactor repo

### ISSUE THREAD

**Issue by Hellebore** [sourcery-ai/sourcery#35]
### Issue description or question

Repo is here:
https://github.com/xnuinside/laziest

### Sourcery Version

Github bot

**Comment by xnuinside** [comment]
Also very cool would be to have some statuses in UI ) to understand that's going on with bot run, but I believe it in plans :)  btw, great idea of the project

**Comment by Hellebore** [comment]
We're getting issues with the GitHub API timing out on our review requests. 

We've raised it with them and will keep this issue updated.

**Comment by Hellebore** [comment]
Still waiting to hear from github support I'm afraid. We have put in a fix so that the bot does the refactorings, but it is missing the explanatory review comments due to the API issue.

**Comment by xnuinside** [comment]
@Hellebore, thanks for updating status :)

**Comment by brendanator** [comment]
@xnuinside This should be fully fixed now. Here's a [fork of laziest](https://github.com/brendanator/laziest/pull/1/files) where it is working

Please let us know if you have any further issues

**Comment by xnuinside** [comment]
@brendanator thank you)
