### ISSUE TITLE
AI-generated docstrings should not be suggested for methods overwriting methods in subclasses or implementing virtual methods

### ISSUE THREAD

**Issue by amogorkon** [sourcery-ai/sourcery#353]
### Description
Working with PyQt6, I often overwrite a method by subclassing a widget, which already has documentation by itself, so adding a docstring would have no benefit. 

### Code snippet that reproduces issue
```
from PyQt6 import QtCore, QtWidgets

class CheckList(QtWidgets.QDialog, ui.task_checklist.Ui_Dialog):
    def __init__(self):
        super().__init__()
        self.setupUi(self)

    def reject(self):
        super().reject()
        ... # cleanup
```
would trigger a quick-fix to add a docstring to `CheckList.reject` since it is a non-trivial public function, but since it inherits the documentation of `QtWidgets.QDialog.reject`, adding a docstring would serve little purpose.
Since in this case the general pattern is to call `super().{method_name}()` in the first line of the block, maybe it would suffice to use a regex to check for this. The method of the base-class would have no call to super(), which would then trigger sourcery to suggest a docstring, satisfying the recursion.

### Sourcery Version
1.3.0

**Comment by Hellebore** [comment]
We now generate docstrings through the recipe system rather than using these.
