### ISSUE TITLE
Coding Assistant is uninterruptible => flow-break

### ISSUE THREAD

**Issue by amogorkon** [sourcery-ai/sourcery#359]
The new coding assistant really is nice in principle, but there are two major problems with the chat.
The main problem is that the assistant can't be skipped/interrupted when you got the answer you're looking for. This means you can't select and copy the snippet the assistant provided, forcing you to wait for the bot to finish. In this moment, the tool slows you down and potentially breaks the flow, which is BAD.
Secondly (which I guess you already are aware of), there's no button to quickly copy a code snippet, which would be nice but not necessarily breaking the flow.

Sourcery Version: 
Version: 1.4.0

Operating system and IDE:
Version: 1.80.0-insider (user setup)
Commit: 49b8e2d5410795e5a23a9c6b7f99b97f4afb4b47
Date: 2023-06-23T13:49:31.833Z
Electron: 22.3.13
ElectronBuildId: 21803499
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19045

**Comment by Hellebore** [comment]
Thanks for the great comments - it's really useful to hear feedback.  

We are planning to tackle both of those issues.

**Comment by amogorkon** [comment]
Just a thought: I figured sourcery uses gpt3 while copilot (which I've also beta-tested and using in parallel) uses codex. That's not a very big difference, so I'm wondering if gpt-4 could be viable for sourcery in the future?

**Comment by Hellebore** [comment]
Fixed with release of 1.6.0
