### ISSUE TITLE
Coding Assistant line-wrap of "Chat" is bad

### ISSUE THREAD

**Issue by amogorkon** [sourcery-ai/sourcery#360]
I'd like to use the coding assistant while in zen-mode, which means that I need the line-wrap of the CHAT (the code-snippets are fine as they are, mostly, although comments could be better line-wrapped, as well) at about 1/3 (about 70-80 characters) of the screen-width or even less, not at about 1/2 like it is now. The longest line of chat text is at 130 characters without wrap AND without horizontal scrollbar, which makes it practically impossible to use the coding assistant without adjusting the size of the side-bar, hiding my own code etc. - it's a hassle.

**Comment by Hellebore** [comment]
Fixed with release of 1.6.0
