### ISSUE TITLE
"Merge dictionary updates via the union operator" should not trigger on collection.Counter

### ISSUE THREAD

**Issue by ronnodas** [sourcery-ai/sourcery#373]
### Checklist

- [x] I have searched the [Sourcery documentation](https://docs.sourcery.ai/) for the issue, and found nothing
- [x] I have checked there are no open [bugs](https://github.com/sourcery-ai/sourcery/issues?q=label%3Abug) referencing the same bug or problem

### Description
If `counts` is a `Counter` (which is a subclass of `dict`) from the `collections` module in the standard library, then `count.update(...)` and `count |= ...` have different semantics, specifically `update()` adds to the values while `|=` replaces the values. The code snippet below prints 2, but on accepting the suggested refactoring it would print 1.

While I understand the refactoring not preserving behavior in arbitrary subclasses, I would expect it to not break on things from the standard library.

### Code snippet that reproduces issue
```python
from collections import Counter

counts = Counter({'a': 1})
counts.update({'a': 1, 'b': 2})
# counts |= {'a': 1, 'b': 2}

print(counts['a']) # prints 2 as is, 1 after refactor
```

### Debug Information

IDE Version: 
PyCharm Professional Edition 2023.2

Sourcery Version: 
Sourcery 1.6.0

Operating system and Version:
Manjaro Linux

**Comment by ablacklama** [comment]
Just encountered this as well. It's a sneaky one. It took me a bit to find why a normal linting commit was breaking my tests!

**Comment by Hellebore** [comment]
Due to this I've downgraded this rule from a refactoring to a suggestion (meaning it doesn't get combined with other rules and needs individual consideration). This change will be in our next release.
