### ISSUE TITLE
Unable to connect to Sourcery executable

### ISSUE THREAD

**Issue by MoHassem** [sourcery-ai/sourcery#38]
### Issue description or question
while editing in Pycharm, I get the error: Unable to connect to Sourcery executable:  expected str, bytes or os.PathLike object, not NoneType

### Sourcery Version
 Plan:  Sourcery Pro.  Plugin version: 0.3.2. Sourcery Version: 0.6.4

### Code editor or IDE name and version

Pycharm 2019.2.5 (Professional Edition)  Build #PY-192.7142.56, November 19, 2019

### OS name and version
Windows 10, running pycharm in WSL 2 on Ubuntu 18.04 LTS

**Comment by Hellebore** [comment]
Thanks for raising - is there anything in particular that caused the issue to occur?

**Comment by MoHassem** [comment]
nothing I can think of, the message appeared two days ago no windows update or ubuntu update.  
I tried enabling and disabling.  uninstall and reinstall

**Comment by MoHassem** [comment]
I  worked on an older project and Sourcery works fine on the project I was working on when I signed up. On  my new project though I get the about error

**Comment by Hellebore** [comment]
We've identified a possible fix - should be a release in the next few days.

**Comment by MoHassem** [comment]
thank you

**Comment by Hellebore** [comment]
We've now released a new version of the Pycharm plugin that hopefully fixes the issue.
Could you please go to File > Settings > Plugins, then click on the update tab and update Sourcery (then restart).
Would be great to know if the issue has been fixed.

**Comment by MoHassem** [comment]
all in order.  Thank  you for the fix
