### ISSUE TITLE
Server Unable to Acquire Lock

### ISSUE THREAD

**Issue by DavidLeber** [sourcery-ai/sourcery#390]
### Checklist

- [X] I have searched the [Sourcery documentation](https://docs.sourcery.ai/) for the issue, and found nothing
- [X] I have read the common issues and fixes listed in the [Sourcery troubleshooting page](https://docs.sourcery.ai/Product/Troubleshooting/#troubleshooting), and found nothing
- [X] I have checked there are no open [bugs](https://github.com/sourcery-ai/sourcery/issues?q=label%3Abug) referencing the same bug or problem

### Description
When I start up Remote VSCode, I get recurring errors that Sourcery server was not able to start up, and I get no recommendations from Sourcery.
![image](https://github.com/sourcery-ai/sourcery/assets/87345286/89227c82-09d0-4157-9ff3-625a5999caa4)

### Debug Information

IDE Version: 
VSCode 1.82.2, developing using RemoteSSH

Sourcery Version: 
Sourcery v1.10.0

Operating system and Version:
Local Machine: Windows 10
Remote Machine: Linux 5.15.0-73-generic x86_64

**Comment by DavidLeber** [comment]
Additional information, when I check the `/tmp/` directory later, I don't see the needed file

**Comment by reka** [comment]
Thanks a lot for reporting this issue.
Do you get this error only when you use RemoteSSH? Or also in a local environment?

**Comment by skethirajan** [comment]
Even I have the same error when I use RemoteSSH. It works fine inside local environment.

**Comment by brendanator** [comment]
Unfortunately, I haven't been able to replicate this. However I guess there's a lack of permissions for the `/tmp` directory within the remote SSH connection.

I've made a change so this lock file is no longer put in the `/tmp` directory but within the Sourcery data directory. I hope this will resolve it

This will be in the next release - please let me know if it doesn't work

**Comment by brendanator** [comment]
Seems like this is now sorted? Closing as completed
