### ISSUE TITLE
Code Lens becomes misaligned after new line

### ISSUE THREAD

**Issue by Magnymbus** [sourcery-ai/sourcery#393]
### Description
Better explained with screenshots.
Every new line offsets the code lens to where the method would be without the line.
![image](https://github.com/sourcery-ai/sourcery/assets/14867244/7567269f-fd90-4424-9e18-0b046cfb6262)

This is what it should be.
![image](https://github.com/sourcery-ai/sourcery/assets/14867244/0f6c619c-765b-459c-8912-99506b70c552)

Related to #394 as the auto-scroll only occurs after the code lens becomes significantly misaligned.

EDIT:
Is resolved on file save, making autosave afterDelay with default delay sufficient to mitigate the issue.

### Debug Information

Operating system and Version:
Windows 11 Home 22H2 (v10.0.22621)

Sourcery Version: 
v1.10.1
v1.10.0

IDE Version: 
VSCode v1.83
VSCode v1.82

Enabled VSCode extensions:
AREPL for python v2.0.5 (Almenon)
autopep8 v2023.6.0 (Microsoft)
Bookmarks v13.4.1 (Alessandro Fragnani)
Formatting Toggle v3.2.0 (tombonnike)
Hex Editor v1.6.12 (Microsoft)
indent-rainbow v8.3.1 (oderwat)
IntelliCode v1.2.30 (Microsoft)
Mintlify Doc Writer v2.2.1 (Mintlify)
Project Manager v12.7.0 (Alessandro Fragnani)
Pylance v2023.9.30 (Microsoft)
Python v2023.16.0 (Microsoft)
Python Environment Manager v1.2.4 (Don Jayamanne)
Python Indent v1.18.0 (Kevin Rose)
Todo Tree v0.0.26 (Gruntfuggly)
vscode-icons v12.5.0 (VSCode Icons Team)

**Comment by Magnymbus** [comment]
It always happens eventually, if you're not working at the bottom of a file. It is resolved on file save, which seems to reset the code lens positions. However, It does NOT resolve with time. Turning off code lens is also a perfectly valid workaround, as long as you aren't using those four links/buttons.

**Comment by Magnymbus** [comment]
If you are unable to reproduce it, it seems likely to be a conflict with settings or with another extension. I'll do some testing.

**Comment by Hellebore** [comment]
Thanks for that @Magnymbus - have now tried it on a Windows machine and can reproduce it - investigating.

**Comment by Hellebore** [comment]
Have put in a fix so this should be addressed in our next release

**Comment by ruancomelli** [comment]
A fix for this issue [has just been released](https://sourcery.ai/changelog/2023-10-31-2023-10-31/).
Thanks for reporting this issue, and please let us know if it happens again!
