### ISSUE TITLE
Code lens causes editor to scroll on input

### ISSUE THREAD

**Issue by Magnymbus** [sourcery-ai/sourcery#394]
### Description
Better explained with a gif:
![2023 10 04 16 20](https://github.com/sourcery-ai/sourcery/assets/14867244/d6f50c84-3d68-4322-b315-b053f59ad4bf)

related to #393 as it only occurs after the code lens is misaligned.

EDIT:
Because this issue only occurs after #393 has occurred, autosave afterDelay with default delay are sufficient to mitigate the issue.

### Debug Information

Operating system and Version:
Windows 11 Home 22H2 (v10.0.22621)

Sourcery Version: 
v1.10.1
v1.10.0

IDE Version: 
VSCode v1.83
VSCode v1.82

Enabled VSCode extensions:
AREPL for python v2.0.5 (Almenon)
autopep8 v2023.6.0 (Microsoft)
Bookmarks v13.4.1 (Alessandro Fragnani)
Formatting Toggle v3.2.0 (tombonnike)
Hex Editor v1.6.12 (Microsoft)
indent-rainbow v8.3.1 (oderwat)
IntelliCode v1.2.30 (Microsoft)
Mintlify Doc Writer v2.2.1 (Mintlify)
Project Manager v12.7.0 (Alessandro Fragnani)
Pylance v2023.9.30 (Microsoft)
Python v2023.16.0 (Microsoft)
Python Environment Manager v1.2.4 (Don Jayamanne)
Python Indent v1.18.0 (Kevin Rose)
Todo Tree v0.0.26 (Gruntfuggly)
vscode-icons v12.5.0 (VSCode Icons Team)

**Comment by ruancomelli** [comment]
A fix for this issue [has just been released](https://sourcery.ai/changelog/2023-10-31-2023-10-31/).
Thanks for reporting this issue, and please let us know if it happens again!
