### ISSUE TITLE
Sourcery creates error on Pycharm Run manage.py task

### ISSUE THREAD

**Issue by charleslstone** [sourcery-ai/sourcery#395]
### Checklist

- [ x] I have searched the [Sourcery documentation](https://docs.sourcery.ai/) for the issue, and found nothing
- [x ] I have read the common issues and fixes listed in the [Sourcery troubleshooting page](https://docs.sourcery.ai/Product/Troubleshooting/#troubleshooting), and found nothing
- [ x] I have checked there are no open [bugs](https://github.com/sourcery-ai/sourcery/issues?q=label%3Abug) referencing the same bug or problem

### Description
With Sourcery enabled, Pycharm reports an error when trying to start Run manage.py task.  With Sourcery disabled, the error does not occur.  Picking between Sourcery and the Pycharm manage.py task is like picking a child to leave behind...I love them both.

The Pycharm error says:  
Exception in plugin Sourcerty (1.10.1)  Disable plugin...[link]
This plugin is not a production of JetBrains.  Please report the problem to Sourcery [link].

This error started in about mid-Sept with a recent release (prior to 1.10.1) and I have had Sourcery disabled since.  Today I saw an update is available and installed it, but the problem persists in this verion also.

### Code snippet that reproduces issue

```python

```

### Debug Information

IDE Version: 

PyCharm 2023.2.1 (Professional Edition)

Sourcery Version: 

Sourcery 1.10.1

Operating system and Version:

Windows 11

**Comment by brendanator** [comment]
Thanks for reporting this @charleslstone. I've fixed this and it will be in the next release

**Comment by charleslstone** [comment]
Brendan, 
Just a follow-up note say thanks for the fix.  I have the most recent release and all seems working fine with Sourcery and Pycharm’s Run manage.py Task.

Much appreciated!
Charlie Stone
