### ISSUE TITLE
Typo in binary operator identity docs

### ISSUE THREAD

**Issue by Andrew-S-Rosen** [sourcery-ai/sourcery#397]
https://docs.sourcery.ai/Reference/Rules-and-In-Line-Suggestions/Python/Default-Rules/bin-op-identity/#binary-operator-identity

"Replaces binary operationss" (note the two "s")

**Comment by ruancomelli** [comment]
Hello, @Andrew-S-Rosen! Thanks for reporting this issue. The type is now fixed :wink:
