### ISSUE TITLE
Sourcery: Scanning Notifications pile up while editing 

### ISSUE THREAD

**Issue by russhughes** [sourcery-ai/sourcery#401]
### Checklist

- [x] I have searched the [Sourcery documentation](https://docs.sourcery.ai/) for the issue, and found nothing
- [x] I have read the common issues and fixes listed in the [Sourcery troubleshooting page](https://docs.sourcery.ai/Product/Troubleshooting/#troubleshooting), and found nothing
- [x] I have checked there are no open [bugs](https://github.com/sourcery-ai/sourcery/issues?q=label%3Abug) referencing the same bug or problem

### Description
Sourcery: Scanning Notifications randomly pile up while editing and do not go away until I restart VSCode. I am logged in and have a valid Token.

![Screenshot from 2023-11-18 19-16-26](https://github.com/sourcery-ai/sourcery/assets/23587382/25dcca9b-b42c-4080-bf47-e13db48781b1)

### Debug Information

IDE Version: 
Visual Studio Code
Version: 1.84.2
Commit: 1a5daa3a0231a0fbba4f14db7ec463cf99d7768e
Date: 2023-11-09T10:50:47.800Z
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Linux x64 5.14.0-362.8.1.el9_3.x86_64

Sourcery Version: 

Operating system and Version:

AlmaLinux 9.3 (Shamrock Pampas Cat) - with all updates.

**Comment by bm424** [comment]
Hi @russhughes, thanks for bringing this to our attention. I've had a look, and this notification should only appear when you're running a scan for a specific rule from the rule search window, so something is clearly going wrong.

As this appears to be an issue that's specific to your installation, please send an email to support@sourcery.ai with your sourcery log file attached ([documentation](https://docs.sourcery.ai/Product/Troubleshooting/#what-is-the-sourcery-log)), and we'll be able to start debugging. I'm going to close this issue on GitHub for now, but please do get in touch - we'd like to fix this as soon as possible.
