### ISSUE TITLE
Project disabled for account due to open source account. I have a pro account

### ISSUE THREAD

**Issue by bakobako** [sourcery-ai/sourcery#407]
### Description
Suddenly the sourcery window says:

```
Logged In: Open Source Account
Project disabled for account
Your Open Source Sourcery account can't be used for private projects.
```

I have a pro license, I press upgrade, and it shows me I have a pro license...

I restarted pycharm, but still had the same issue.
I uninstalled and reinstall Sourcery, does not resolve the issue

### Debug Information

IDE Version: 
PyCharm 2023.2.5 (Professional Edition)

Sourcery Version: 
Sourcery 0.14.0

Operating system and Version:
Sonoma 14.1.2 (M2 Mac)

**Comment by bm424** [comment]
Discussing via email.
