### ISSUE TITLE
Sourcery deletes useful code

### ISSUE THREAD

**Issue by iphydf** [sourcery-ai/sourcery#41]
### Issue description or question

```python
    while run_mallocfail(exe, timeout):	
        pass
```

I could rewrite this to say

```python
while True:
  if run_mallocfail(exe, timeout):
    pass
```

but really sourcery should only do safe refactorings.

See https://github.com/TokTok/toktok-stack/pull/94/commits/fc31fd8908c6098f8caaf6960091026970e3edfc#diff-9943d64762e22ec9d53b7aec416b9c29L82

**Comment by Hellebore** [comment]
Yep - this is a bug. Thanks for raising - we will look to address it as soon as we can.

**Comment by Hellebore** [comment]
Have identified a fix - will be in our next release.

**Comment by Hellebore** [comment]
This is now live in pycharm - vscode to follow shortly.
