### ISSUE TITLE
VS Code: Couldn't create connection to server to Sourcery at startup

### ISSUE THREAD

**Issue by charlesmartineau** [sourcery-ai/sourcery#416]
I just upgraded from a Mac M1 to M3. When I load VS Code, I get the following message 
<img width="439" alt="image" src="https://github.com/sourcery-ai/sourcery/assets/1816735/5535525e-0be6-437b-bf32-a65241fd6f86">
<img width="1263" alt="image" src="https://github.com/sourcery-ai/sourcery/assets/1816735/ae9232d5-f46f-41be-875a-5223b53963b1">

Because of this issue, cmd+shift+p then sourcery:login, I get this:

<img width="248" alt="image" src="https://github.com/sourcery-ai/sourcery/assets/1816735/5078320f-94d9-4081-95c6-5c6becde5168">

I had no such issues with my Mac M1... could this issue be specific to M3? How can this be resolved? 

Thank you,

### Debug Information

IDE Version: 
VS Code

Sourcery Version: 
Sourcery 1.15

Operating system and Version:
Mac OS Sonoma

**Comment by brendanator** [comment]
It looks like the Sourcery executable cannot run. Do you have Rosetta installed on your M3?

**Comment by charlesmartineau** [comment]
ah thank god! this was the solution. thank you so much!
