### ISSUE TITLE
MacOs PyCharm Plugin stuck at "Loading"

### ISSUE THREAD

**Issue by xArbisRox** [sourcery-ai/sourcery#419]
### Checklist

- [x] I have searched the [Sourcery documentation](https://docs.sourcery.ai/) for the issue, and found nothing
- [x] I have read the common issues and fixes listed in the [Sourcery troubleshooting page](https://docs.sourcery.ai/Product/Troubleshooting/#troubleshooting), and found nothing
- [x] I have checked there are no open [bugs](https://github.com/sourcery-ai/sourcery/issues?q=label%3Abug) referencing the same bug or problem

### Description
After installing the Plugin, the Sourcery Tool Window gets stuck at "Loading".
<img width="479" alt="image" src="https://github.com/sourcery-ai/sourcery/assets/106534515/74038727-7447-4cb0-8223-e8c592b8e3c4">

Pressing the "Login" (via Browser) Button at Tools --> Sourcery does nothing. 

Expected to be able to Login after Plugin installation.

Un-, Reinstalling the Plugin and restarting the application does not solve the issue

### Debug Information

IDE Version: 
PyCharm 2023.3.3 (Professional Edition)

Sourcery Version: 
Sourcery 1.15.0

Operating system and Version:
macOS 14.2.1

**Comment by Hellebore** [comment]
Hi @xArbisRox - sorry you're having trouble.

The first thing to try is making sure rosetta is installed:
https://docs.sourcery.ai/Product/Troubleshooting/#sourcery-not-working-on-apple-m1

If that's not the issue then it would be good to see your log file - please send it through to `support@sourcery.ai`
https://docs.sourcery.ai/Product/Troubleshooting/#what-is-the-sourcery-log

**Comment by xArbisRox** [comment]
Hi @Hellebore ,
thanks for your sharp feedback.
To be honest - I was quite sure that I already installed Rosetta via the UI - seems like it wasn't. Installing it via CLI now solved the issue for me and the plugin is working.
Just want to note, that this issue seems to also occur on the Apple M2, and not only on the M1 as noted in the documentation.
