### ISSUE TITLE
review doesn't work on organization's repo

### ISSUE THREAD

**Issue by cnlangzi** [sourcery-ai/sourcery#421]
### Checklist

- [x] I have searched the [Sourcery documentation](https://docs.sourcery.ai/) for the issue, and found nothing
- [x] I have read the common issues and fixes listed in the [Sourcery troubleshooting page](https://docs.sourcery.ai/Product/Troubleshooting/#troubleshooting), and found nothing
- [x] I have checked there are no open [bugs](https://github.com/sourcery-ai/sourcery/issues?q=label%3Abug) referencing the same bug or problem

### Description
Install sourcery-ai on organization, and grant permission on some public repos.  review doesn't work on new pull request. https://github.com/yaitoo/sqle/pull/25

### Code snippet that reproduces issue

```python

```

### Debug Information

IDE Version: 

Sourcery Version: 

Operating system and Version:

**Comment by brendanator** [comment]
@cnlangzi Which PR were you expecting a review on and didn't get one?

**Comment by cnlangzi** [comment]
> @cnlangzi Which PR were you expecting a review on and didn't get one?

eg https://github.com/yaitoo/sqle/pull/25 . The bot should review any new PR , right?
I see it works like a charm on https://github.com/avelino/awesome-go/pull/5240

**Comment by brendanator** [comment]
Hi @cnlangzi - this PR was created by a bot and we intentionally don't review any pull requests created by bots

Would you find a comment useful saying we have skipped the PR?

**Comment by cnlangzi** [comment]
> Hi @cnlangzi - this PR was created by a bot and we intentionally don't review any pull requests created by bots
> 
> Would you find a comment useful saying we have skipped the PR?

good job. it works. but there is a bug on reviewing. https://github.com/sourcery-ai/sourcery/issues/423
