### ISSUE TITLE
feat: review should be updated or create a new one.

### ISSUE THREAD

**Issue by cnlangzi** [sourcery-ai/sourcery#427]
### Checklist

- [x] This is a new feature, not a refactoring suggestion
- [x] I have checked for this feature in the [Sourcery documentation](https://docs.sourcery.ai/)
- [x] I have checked there are no open [requests](https://github.com/sourcery-ai/sourcery/issues?q=label%3Aenhancement) referencing the same feature

### Description
for now, sourcery ai create review as comment. It is impossible to click `request re-review`. and the review will be out of date if any new commit is pushed. 
could we update it or create a new one with latest code again?

**Comment by Hellebore** [comment]
@cnlangzi thanks for raising - this is on our roadmap and coming up shortly.

How would you prefer to request a re-review?
Options we're considering (also open to others):
- comment something like `@sourcery-ai review`
- adding a label
- a checkbox in our summary comment

**Comment by cnlangzi** [comment]
> @cnlangzi thanks for raising - this is on our roadmap and coming up shortly.
> 
> How would you prefer to request a re-review? Options we're considering (also open to others):
> 
> * comment something like `@sourcery-ai review`
> * adding a label
> * a checkbox in our summary comment

like as human review, we will ask him to re-review when code is updated based on his comments. 

 ` @sourcery-ai review ` make senses.  Maybe it is easier to do it automatically if code is updated. 
eg [dependabot](https://github.com/apps/dependabot), [deepsource-io](https://github.com/apps/deepsource-io) or [codecov](https://github.com/apps/codecov).

on dependabot, comment commands are optional. I just write it when I want to trigger it start task immediately.

re review, to use [built-in feature](https://github.blog/changelog/2019-02-21-re-request-review-on-a-pull-request/) should be more friendly than new comment commands/label...etc.

**Comment by ruancomelli** [comment]
Hello, @cnlangzi!

We recently released an update that allows you to request new reviews from Sourcery. Just comment
```
@sourcery-ai review
```
on a PR, and the Sourcery bot will start a new review.

Unfortunately, the built-in re-request feature can only be used to re-request reviews from human reviewers, not bots (like Sourcery).

Thanks for reaching out!

**Comment by cnlangzi** [comment]
@ruancomelli  it seems don't work properly. please check https://github.com/yaitoo/sqle/pull/47#pullrequestreview-2111727897

A new `null.go` file was added. but the robot says it is reviewed.

**Comment by ruancomelli** [comment]
Hey @cnlangzi! This looks like a bug in the re-review mechanics. I opened a new GitHub issue to track this down: https://github.com/sourcery-ai/sourcery/issues/428#issue-2351803855.
