### ISSUE TITLE
PR review bot: Possible to disable "overall comments" and line-level suggestions?

### ISSUE THREAD

**Issue by blakeNaccarato** [sourcery-ai/sourcery#439]
### Checklist

- [x] This is a new feature, not a refactoring suggestion
- [x] I have checked for this feature in the [Sourcery documentation](https://docs.sourcery.ai/)
- [x] I have checked there are no open [requests](https://github.com/sourcery-ai/sourcery/issues?q=label%3Aenhancement) referencing the same feature

### Description

I like the PR summarizing/digest features of the AI review bot, and think it could be helpful as a "rough draft" review summary. However, I would really like to disable the line-level scrutiny, comments, and improvement suggestions of the review bot.

Regardless of the quality or tone of these suggestions, I'd like to have a policy in my projects that the quality of PRs submitted by others isn't directly assessed by the bot, which I think can be a bit impersonal and off-putting. Besides, any invalid/excessive suggestions may generate churn and unnecessary commits in an attempt to "appease" our robot overlords 😅 before a human reviewer gets around to it.

I tried passing the following to the "instructions" dashboard section, but review comments were still made. I left the path glob empty so maybe that needs to be `**/*` or `*` or something, or those instructions do not affect the actual comment mechanism itself.

```
- Please do not make any comments.
- Please do not give any suggestions for improvement.
```

Anyways, I appreciate that the other toggles are present, and I imagine the review comments are the "first line

**Comment by ruancomelli** [comment]
Hello, @blakeNaccarato!

Currently, our review instructions can only be used to generate additional review comments, not to suppress comments that it already generates by default. That's in our roadmap, but it's not available yet.

However, we now have an option to completely disable AI review comments. Please head over to [your Sourcery dashboard](https://sourcery.ai/dashboard/#review-settings) and un-toggle the "Enable AI review comments" option:

![Image](https://github.com/user-attachments/assets/ca428bec-d4a7-4027-a2fb-093412ea6839)

**Comment by blakeNaccarato** [comment]
Ah, alright I see that toggle now. Must've escaped me when I first raised the issue. Thanks for your help!
