### ISSUE TITLE
Sourcery shows CI failures in the commit list

### ISSUE THREAD

**Issue by rec** [sourcery-ai/sourcery#44]
### Issue description or question

The tool leaves false CI failures in your commit record, which is bad for projects that pride themselves on no failures (like mine)

e.g. https://github.com/rec/safer/commits/master - only one red X in over 100 commits and it's from you.

I signed up with six projects and now I have five failures on my otherwise clean record.

### Sourcery Version

Often available in Sourcery settings

### Code editor or IDE name and version

Github

### OS name and version

n/a

**Comment by brendanator** [comment]
Yes, you are right. It doesn't make any sense to add check statuses to branch refactorings like this. We will restrict it to PR commits only, where it does make sense.

Sorry for spoiling your clean record

**Comment by brendanator** [comment]
This is now fixed and deployed, let me know if you encounter any issues

**Comment by rec** [comment]
Whoa, friction burns!  That's super-fast.

This is a great idea, by the way.  I'm super-clean code and it found a couple of small improvements that were definitely a tiny bit better.  I'll bet on a code base with multiple developers you'd find all sorts of bad things.

Thanks for doing this!
