### ISSUE TITLE
Could not get token to use on vscode

### ISSUE THREAD

**Issue by edumco** [sourcery-ai/sourcery#46]
### Code editor or IDE name and version

VSCODE

### OS name and version

Linux Ubuntu 20,4

**Comment by xatier** [comment]
same here, not able to see tokens after login with GitHub.

**Comment by brendanator** [comment]
This is now fixed, return to https://sourcery.ai/download/ and your token should be available (you may need to refresh the page).

Sorry for the inconvenience, we just deployed major changes to the site and broke some of the external links. Thanks for reporting

**Comment by xatier** [comment]
@brendanator my vscode now shows "invalid" token, is there a way to refresh for a new token?

**Comment by brendanator** [comment]
@xatier Email me at brendan@sourcery.ai and I'll investigate

**Comment by edumco** [comment]
> @brendanator my vscode now shows "invalid" token, is there a way to refresh for a new token?

Try reinstall the plugin so it removes the cached contents
