### ISSUE TITLE
Scientific notation is not retained

### ISSUE THREAD

**Issue by pmeier** [sourcery-ai/sourcery#50]
### Issue description or question

Consider the following snippet:

```python
if foo:
    bar = 1e-4
else:
    bar = 1e15
```

This gets refactored to 

```python
bar = 0.0001 if foo else 1000000000000000.0
```

which is correct but quite cumbersome. If you decrease or increase the exponent any further, the scientific formatting is retained:

```python
if foo:
    bar = 1e-5
else:
    bar = 1e16
```

```python
bar = 1e-05 if foo else 1e+16
```

### Sourcery Version

Sourcery Starbot (see https://github.com/pmeier/pystiche/pull/270/files#r433867794)

**Comment by brendanator** [comment]
Thanks for the report. This is now fixed in the latest deployed GitHub bot. Will be in next plugin releases
