### ISSUE TITLE
Support for Black

### ISSUE THREAD

**Issue by danyeaw** [sourcery-ai/sourcery#51]
My repositories all use Black for code formatting, and it has become somewhat of a standard across Python projects.

Issue: The Sourcery bot makes code formatting suggestions that don't pass the black pre-commit hooks in the linting stage of CI because the suggestions use single quotes for strings and other formatting problems. This requires then fetching the proposed changes, running the pre-commit hooks, and pushing the changes back to the branch.

Possible solutions:
1. Detect use of black in the project and make formatting suggestions match that formatting or run black on the code changes after initially reformatting
2. Add a use black setting to the bot
3. Detect the formatting of the code that is being updated and try to match it
4. Use black for code formatting all the time

**Comment by brendanator** [comment]
We currently try to do option 3 as we think it should work for most people most of the time but there are some limitation of that approach.

Having looked at the PR that you reformatted with black I can see 4 issues:
1. Double quotes replaced with single quotes
2. Comments being misaligned
3. Extra indents being added inside multiline if conditions and for iterators
4. Refactored code being formatted to a different line length

Definitely 1 should never happen and I've identified a fix that should mean that all strings (and other constants) always are output the same as they existed in the original source.

2 and 3 are bugs that I'll need to look into more to see where the extra spaces are coming from. 

4 is more difficult as it's hard to guess what the expected line length is so Sourcery just uses a default of 80 chars.

For now I will try and fix the first 3 problems. It does seem like allowing configuration to specify the formatter (yapf also comes to mind) will be needed to solve this fully.

**Comment by pmeier** [comment]
> 4 is more difficult as it's hard to guess what the expected line length is so Sourcery just uses a default of 80 chars.

That might be a problem since `black` uses a default of 88.

**Comment by brendanator** [comment]
Yes, it's tricky, there's a variety of defaults:
- PEP8 is 79
- YAPF Google/Facebook styles are 80
- Black is 88

Writing this out makes me think it will have to be configurable in some way. Will have a think how best to do it.

**Comment by brendanator** [comment]
Issues 1, 2 and 3 have now been fixed. The fixes are already in the GitHub bot and will be in the next IDE plugin release

**Comment by WayneLambert** [comment]
With regards to number 4, iSort uses a `profile` property if you'd like to match with your Black config and a `line_length` property if you would like to customise.

It seems to me that this could be considered in line with the development of the feature for using a pyproject.toml (#159).

I sometimes have to reject refactorings based upon small stuff like this.

Also, I have had refactorings generated by the GitHub bot within the last 3-4 days where an f-string suggestion was given which changed my single quotes into double quotes, so I'm not sure number 1 is fixed.

Unfortunately, I have now deleted the branch so I cannot give you the example.

**Comment by WayneLambert** [comment]
Hi @brendanator,

Further to my above comment, I do actually have the PR [https://github.com/WayneLambert/portfolio/pull/137](https://github.com/WayneLambert/portfolio/pull/137) which has refactored the f-string using single quotes instead of double quotes, therefore I'm not so sure that issue number 1 has been resolved.

**Comment by danyeaw** [comment]
Sourcery has been working great for me over the last year in multiple projects using Black and flake8. I am going to go ahead and close this issue. If others find specific issues where it isn't working, I recommend opening a new issue.
