### ISSUE TITLE
Strange string repetition (list.append)

### ISSUE THREAD

**Issue by Aurexine** [sourcery-ai/sourcery#54]
### Issue description or question
Using the Github Star Bot to create a pull request, there is a strange artifact where strings are duplicated upon condensing a series of `list.append()` calls into a single `return [list, content]`.

See (Actual output): https://github.com/Aurexine/discord-bot/pull/4/commits/528fcfb8909296b012cae5f416c3d90c84c25910#diff-5bc02cefb3ea9e27f1a6776eabd1935dL91

Fixed (Expected output): https://github.com/Aurexine/discord-bot/commit/b9c5db1f97dd69b83f6aab7a45e667781a8e9cf6

### Sourcery Version
sourcery-ai-bot via github star, I don't see a version listed anywhere

I've omitted the n/a sections of the default issue since I did not use sourcery locally, only through the github star bot.

**Comment by brendanator** [comment]
Thanks for the report. That's a really horrible piece of output, it looks like the whole f string is being re-inserted at the start of each new interpolation. I'll investigate

**Comment by Hellebore** [comment]
Now fixed in all versions.
