### ISSUE TITLE
Failed to launch Sourcery service: Cannot run program

### ISSUE THREAD

**Issue by komodovaran** [sourcery-ai/sourcery#56]
### Issue description or question
PyCharm tells me that
```
09:38	Failed to launch Sourcery service: Cannot run program "C:\Users\usr\AppData\Local\JetBrains\Toolbox\apps\PyCharm-C\ch-0\201.7223.69.plugins\pycharm-plugin\lib\win\sourcery.exe" (in directory "C:\Users\usr\AppData\Local\JetBrains\Toolbox\apps\PyCharm-C\ch-0\201.7223.69.plugins\pycharm-plugin\lib\win"): CreateProcess error=5, Access is denied
```

I've tried uninstalling and reinstalling, and running PyCharm as admin, but neither helps.

### Sourcery Version
Plugin version 4. Sourcery version 7.

### Code editor or IDE name and version

Pycharm 2020.1.1 RC (Installed from Toolbox).

### OS name and version

Windows 10 build 1909.

**Comment by Hellebore** [comment]
Hi! Thanks for letting us know about this - did it just start happening, or has Sourcery never worked for you?

I will investigate installing PyCharm through the toolbox on Windows to see if that helps me reproduce the issue.

**Comment by komodovaran** [comment]
I'm positive that it has worked before, and I've used Toolbox since day 1 on this machine.

**Comment by Hellebore** [comment]
Oh interesting - did you recently do an update of PyCharm or Sourcery?

**Comment by komodovaran** [comment]
Just tried clean install of PyCharm as 2020.2 EAP and reinstalled Sourcery from the Marketplace. Same issue,

**Comment by Hellebore** [comment]
Apologies for the delay - haven't been able to reproduce this unfortunately.

If you navigate to the C:\Users\usr\AppData\Local\JetBrains\Toolbox\apps\PyCharm-C\ch-0\201.7223.69.plugins\pycharm-plugin\lib\win on the command line and run 'sourcery.exe --version' what output do you get?

**Comment by komodovaran** [comment]
The version is 0.7.3.

Sorry for not getting back. It seems to be working now, on 2020.2 EAP. I can't say which specific version fixed it, or if it ever was a version issue. Close until further evidence surfaces?

**Comment by brendanator** [comment]
Glad it's working again for you. Closing until it recurs
