### ISSUE TITLE
try-catch block causes unsafe refactoring

### ISSUE THREAD

**Issue by atkaiser** [sourcery-ai/sourcery#58]
### Issue description or question

Sourcery was trying to do a refactor that changed the result of my code. Here is simplified test case.  The original code looked like:

```
test = True
for _ in range(2):
    for _ in range(2):
        if test:
            try:
                print("Hello")
            except:
                pass
    test = False
```

Which when run prints:
```
Hello
Hello
```

Sourcery wanted to refactor it for the reason "Hoist statements out of for/while loops", and changed my code to:
```
test = True
test = False
for _ in range(2):
    for _ in range(2):
        if test:
            try:
                print("Hello")
            except:
                pass
```
Which doesn't print anything when run it.

It seems like the problem has something to do with the the try-catch block, because if I take that out of the test case it doesn't try and do the refactoring anymore.

![sourcery-bug](https://user-images.githubusercontent.com/1351576/85186458-fa501680-b24d-11ea-9e31-54edbc90a7bc.jpg)

### Sourcery Version

Version 0.2.5

### Code editor or IDE name and version

Version: 1.46.1

### OS name and version

OSX - 10.15.5

**Comment by Hellebore** [comment]
Definitely an issue - can reproduce and will address.

**Comment by Hellebore** [comment]
Fix identified. Will be in next release.

**Comment by Hellebore** [comment]
Resolved in latest plugin releases.
