### ISSUE TITLE
Github code review not working on repos with Jupyter notebooks?

### ISSUE THREAD

**Issue by weiji14** [sourcery-ai/sourcery#59]
### Issue description or question

Hi there, just wanted to post this issue here on Github instead of replying via email (thanks for reaching out by the way). I noticed that Sourcery seems to only work on 'pure' Python repos, not ones with Jupyter notebooks (*.ipynb) mixed with Python (*.py) scripts?

For example, after starring the sourcery repo, a pull request was opened up at https://github.com/weiji14/pyissm/pull/1, which is indeed my [top (and only) pure Python repo](https://github.com/weiji14?tab=repositories&q=&type=source&language=python), and that's fine. But when I tried adding one of my other repos at https://github.com/weiji14/deepicedrain which is 1.5% Python and ~88% Jupyter notebook, and clicked manually on the 'Refactor master' button in the Web UI, nothing happens.

I'm currently using [jupytext](https://github.com/mwouts/jupytext) to pair my Jupyter notebooks and Python scripts, and though I don't expect Sourcery to work on Jupyter notebooks anytime soon, it would be nice if it can look at the Python scripts at least.

### Sourcery Version

Online Github Code Review

**Comment by Hellebore** [comment]
Thanks for raising the issue - if there are Python scripts mixed in it should be looking at them. 

I'll look into it and get back to you.

**Comment by Hellebore** [comment]
Hi there - have gotten to the bottom of this. It looks like Sourcery did scan your deepicedrain repo, but wasn't able to find any refactorings that it could do. 

We've been improving the feedback on the website for when this happens - you can now click on your repos to see the history of refactoring jobs and how many they found.

**Comment by weiji14** [comment]
Ah cool, I can see it in the UI now, and also noticed it tried to refactor one of my PRs.

![Sourcery trying to refactor a Github Repo](https://user-images.githubusercontent.com/23487320/86897344-60e49800-c15b-11ea-9757-5bee6b8693a5.png)

Thanks for taking the time to investigate, and sorry for the false alarm.
