### ISSUE TITLE
Sourcery Displays Unrequired Refactorings in VS Code's Problems Panel

### ISSUE THREAD

**Issue by WayneLambert** [sourcery-ai/sourcery#61]
### Issue description or question

The problems detection panel in VS Code picks up on refactoring issues within Python files in a virtual environment's directory. In my case, this is a `.venv` folder created by `pipenv`.

The plugin could do with some settings to ignore certain glob patterns of directories that you do not want Sourcery to inspect.

I checked this in the VS Code user settings and could not find such a setting. I also checked the website, repo and docs and could not find something like a product roadmap which said that this is in the pipeline as a planned feature.

### Sourcery Version

0.3.0

### Code editor name

Editor: VS Code
Version: 1.46.1
Commit: cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
Date: 2020-06-17T21:17:14.222Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.5.0

### OS name and version

Mac OS Catalina 10.15.5 (19F101)

**Comment by Hellebore** [comment]
Hi - you can set up an ignore pattern on a project-by-project basis at the moment using a .sourcery.yaml file - detailed here:
https://github.com/sourcery-ai/sourcery/wiki/Sourcery-configuration

I agree it would be good to have global ignore settings as well.

**Comment by WayneLambert** [comment]
Thanks for coming back to me so quickly. Now that I read the docs, it makes sense that you would need a .yml or .json file committed to source control so that the GitHub scanning could work.

It's a great plugin/tool by the way. Good luck with it progressing and I'll be excited to see how this progresses going forward. It definitely has the potential to do for refactoring what Pylint has done for linting or for what Black has done for formatting.
