### ISSUE TITLE
Password reset email not being sent

### ISSUE THREAD

**Issue by br3ndonland** [sourcery-ai/sourcery#62]
### Issue description or question

I click "Don't remember your password" on the Auth0 login screen at https://auth.sourcery.ai/login, and then enter my email address for a password reset.

The `POST` to `https://auth.sourcery.ai/dbconnections/change_password` returns a `200`, and I see the UI message "Welcome {username}! We've just sent you an email to reset your password." However, I don't get the password reset email. It's not in my spam or trash folders.

### Sourcery Version

0.3.0

### Code editor or IDE name and version

VSCode 1.46.1

### OS name and version

OSX 10.15.5 "Catalina"

**Comment by brendanator** [comment]
Thanks for spotting this. I've changed some config that should have fixed this. Could you try again please

**Comment by br3ndonland** [comment]
It's working! I successfully reset my password. Thanks!
