### ISSUE TITLE
Specify files to be ignored completely by sourcery

### ISSUE THREAD

**Issue by AAraKKe** [sourcery-ai/sourcery#63]
### Issue description or question
I have a project were we setup a virtual environment to work with which is located within the same directory of the project. In this way any development tool we need and that needs to know where the environment is (like python extension in VSCode) can be configured for the team and committed to the repo in any settings file.

The issue is that sourcery scans every python file in this virtual environment and I cannot seem to find a way of telling sourcery to exclude the `.venv` directory. I have checked the documentation but what I find is how to globally turn off specific types of refactoring but not files or folders like in a `.gitignore` fashion.

### Sourcery Version

0.3.0

### Code editor or IDE name and version

VSCode 1.46.1

### OS name and version

MacOS Catalina (10.15.5)

**Comment by brendanator** [comment]
You can use the `ignore` config option as documented [here](https://github.com/sourcery-ai/sourcery/wiki/Sourcery-configuration#ignore)

**Comment by AAraKKe** [comment]
I am so sorry! I swear I only saw the skip option but that was not doing what I wanted. That should do the trick, thanks a lot!

**Comment by brendanator** [comment]
No problemo!
