### ISSUE TITLE
Failed to launch Sourcery service

### ISSUE THREAD

**Issue by thecesrom** [sourcery-ai/sourcery#69]
### Issue description or question
Error occurs when opening a project.

I have tried all of the following and the issue persits:

1. Uninstall/Reinstall Sourcery
2. Deleted the `sourcery` folder from `~/Library/Application Support/JetBrains/PyCharmCE2020.2/plugins` and reinstalled
3. Deleted the `plugins` folder from `~/Library/Application Support/JetBrains/PyCharmCE2020.2` and reinstalled

**Sourcery Refactoring Suggestions**
```
java.util.concurrent.ExecutionException: org.eclipse.lsp4j.jsonrpc.JsonRpcException: java.io.IOException: Stream closed Please retry using the refresh button.
```

**Event Log**
```
Failed to launch Sourcery service: java.util.concurrent.ExecutionException: org.eclipse.lsp4j.jsonrpc.JsonRpcException: java.io.IOException: Stream closed
```

### Sourcery Version

0.7.7

### Code editor or IDE name and version

PyCharm 2020.2 (Community Edition)

### OS name and version

macOS 10.15.6

### Screenshots

![Screen Shot 2020-07-29 at 19 46 05](https://user-images.githubusercontent.com/19418023/88874577-3fb01e00-d1d4-11ea-942b-5b9718618bcc.png)

**Comment by Hellebore** [comment]
Thanks for the report and sorry about the issues! I've rolled back the update to Sourcery while I investigate.

Could you uninstall and reinstall the plugin to check it reverts to 0.7.5 and see if that works?

**Comment by thecesrom** [comment]
Reinstalled 0.7.5 and it is working without any problems.

Thank you.
