### ISSUE TITLE
"Refactor master" doesn't do anything. Refactoring jobs are created with Invalid Date

### ISSUE THREAD

**Issue by wblondel** [sourcery-ai/sourcery#74]
### Issue description or question

Hi,

I signed up on the Sourcery website and installed the app on GitHub. All the permissions seem to be set correctly.
When I go on my list of repositories and click on "Refactor master", a refactoring job is created with the following info:

Created | Type | Status | Branch | Base PR number | # Refactorings | Head PR number
-- | -- | -- | -- | -- | -- | --
Invalid Date | refactor_branch | SUCCESS | master |   | 0 |  

And it never changes. Nothing is created or published on my repo neither.

Am I doing something wrong? I don't get why it doesn't work.

Thank you.

### Sourcery Version

I use the website. I just wanted to try the product.

### Code editor or IDE name and version

Not applicable.

### OS name and version

Not applicable.

**Comment by brendanator** [comment]
It looks like you are doing everything correctly. 

The 2 repos you have tried it on appear to be very short, well written scripts. Sourcery hasn't found any refactorings which is why the `# Refactorings` column is reporting 0.

Sourcery tends to find refactorings on longer, less well written code than yours. Good news that your code is good but a shame that Sourcery hasn't found any improvements for you

**Comment by brendanator** [comment]
I will look into the invalid date issue which seems to be separate. Thanks for reporting

**Comment by wblondel** [comment]
> 
> 
> It looks like you are doing everything correctly.
> 
> The 2 repos you have tried it on appear to be very short, well written scripts. Sourcery hasn't found any refactorings which is why the `# Refactorings` column is reporting 0.
> 
> Sourcery tends to find refactorings on longer, less well written code than yours. Good news that your code is good but a shame that Sourcery hasn't found any improvements for you

Okay, I understand. Maybe the result message should be more explicit?
I'll try on bigger projects 😄 


> 
> 
> I will look into the invalid date issue which seems to be separate. Thanks for reporting

No problem! Thank you.
