### ISSUE TITLE
Cannot access Github repos via Chrome or Firefox

### ISSUE THREAD

**Issue by joecummings** [sourcery-ai/sourcery#78]
### Issue description or question

Appears to be a CORS prblem, which is why I'm opening an issue to see if you guys are aware or I'm doing something wrong.
```
Access to fetch at 'https://api.sourcery.ai/account' from origin 'https://sourcery.ai' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

Steps to recreate:
1. Open Firefox
2. Navigate to `https://sourcery.ai/`
3. Login with Github
4. Grant access to select public repositories
5. Click on "Github Code Review" tab

On the page, I see
<img width="1138" alt="Screen Shot 2020-08-19 at 8 55 51 AM" src="https://user-images.githubusercontent.com/20175092/90643953-c9fb0900-e1f9-11ea-9344-0878f313dff3.png">

### Sourcery Version

N/A

### Code editor or IDE name and version

N/A

### OS name and version

OSX Catalina

**Comment by joecummings** [comment]
Update: works on Safari. Testing out more scenarios like deleting cookies/cache on Firefox and Chrome.

**Comment by brendanator** [comment]
Thanks for the report. I'm looking into this

**Comment by brendanator** [comment]
Have sent you an email asking for a few more details as I'm unable to reproduce it here

**Comment by joecummings** [comment]
"...we were running a huge number of large database requests throughout today that I have asked the person responsible to stop." - @brendanator 

Closing because the requests must've decreased and the issue was resolved.
