### ISSUE TITLE
Refactor two assignments into one

### ISSUE THREAD

**Issue by marcoaaguiar** [sourcery-ai/sourcery#88]
### Issue description or question
I was working in our code base and I found an improvement that was not suggested by Sourcery.

Sourcery could suggest to use a single assignment when two assignments points to the same object in the sequence, that is
```python
def f():
    x = 2 + 2

    a = x
    b = x

    return a + b
```

Could be refactored
```python
def f():
    x = 2 + 2

    a = b = x

    return a + b
```
Don't mind the dumb example :)

I guess this one falls into the enhancement category.

### Sourcery Version
0.8.0

### Code editor or IDE name and version

Discovered on NeoVim 0.5.0

### OS name and version

Ubuntu 20.04 via WSL

**Comment by Hellebore** [comment]
Thanks! We love suggestions - will add it to our pipeline.

**Comment by Hellebore** [comment]
Added to the backlog for investigation.
