### ISSUE TITLE
Quality warnings in PyCharm Problems pane show as raw HTML

### ISSUE THREAD

**Issue by nerdeverde** [sourcery-ai/sourcery#90]
### Issue description or question
When Code Quality metrics are enabled and a function has exceeded the configured quality_threshold, a Warning is flagged on the function in question (as expected). In the editor popup, the quality report is displayed as expected, but in the Problems view for the given file, the warning displays the raw HTML of the quality report. When hovering over the line in the Problems pane, the tooltip will extend well outside of the PyCharm window. The warning should probably show only the function name and the overall quality score.

### Sourcery Version
0.8.1

### Code editor or IDE name and version
PyCharm 2020.2.2 

### OS name and version
macOS 10.15.6

**Comment by Hellebore** [comment]
Thanks for the report! Will look into this now.

**Comment by Hellebore** [comment]
Fix identified - will be in the next release.

**Comment by Hellebore** [comment]
Fixed with 0.8.2 release.
