### ISSUE TITLE
Sourcery plugin not starting using IntelliJ IDEA on Ubuntu

### ISSUE THREAD

**Issue by Hellebore** [sourcery-ai/sourcery#91]
### Issue description or question

Sourcery crashes when loading up using IntelliJ IDEA 2020.2.3 on Ubuntu 20.04.

Able to access https://api.sourcery.ai/health on the machine.

### Sourcery Version

0.8.1

### Code editor or IDE name and version

IntelliJ IDEA 2020.2.3

### OS name and version

Ubuntu 20.04

**Comment by KevinVinsen** [comment]
It also happens on Ubuntu 20.10

**Comment by brendanator** [comment]
I haven't been able to reproduce this. Is it still happening in 0.8.2?

**Comment by KevinVinsen** [comment]
The problem goes away in 0.8.2

**Comment by brendanator** [comment]
Thanks @KevinVinsen
