### ISSUE TITLE
Add LICENSE to clarify reusability

### ISSUE THREAD

**Issue by Daniel-Mietchen** [sourcery-ai/sourcery#94]
### Issue description or question

There is no statement about the licensing of the code in this repo. It should preferably be a standard license (ideally [OSI-approved](https://opensource.org/licenses)) and added as a dedicated file.

**Comment by ADI10HERO** [comment]
@brendanator 
Can I take this up? 
Let me know which license you'd wanna go with and I can make a quick PR :)

**Comment by brendanator** [comment]
There's very little code in this repo but can give it a license. 

@ADI10HERO Yes, please, very happy to take a PR on this. Let's go with MIT

**Comment by ADI10HERO** [comment]
Works @brendanator  
Thank you for letting me take this 

```
MIT License

Copyright (c) [year] [fullname]

...
```

`Replace [year] with the current year and [fullname] with the name (or names) of the copyright holders.`

For year shall I write 2020? 

In popular repositories it's of the form `start_year - current_year` (my guess) see [1](https://github.com/angular/angular.js/blob/master/LICENSE)

Also please let me know the name/names of the copyright holders

Thanks :)

**Comment by brendanator** [comment]
These values should do it:
- year = 2020
- fullname = SOURCERY.AI LIMITED

Thanks!
